### ISSUE TITLE
Game Crash when Breaking Sophisticated Barrels

### ISSUE THREAD

**Issue by DarkWolfLinux** [The-Nexus-Project/Limitless-5#101]
Forces a dc/crash when breaking sophisticated barrels on server.  Tried different upgrades of Barrels (base-diamond) and variants(Oak,spruce,etc) and causes the game to crash.  This happens immediate on left clicking the barrel. Can break with a projectile dig spell from Ars.

**Comment by Gbergz** [comment]
Fixed next update, will probably release a hotfix (.1 update) before the next big update though.

**Comment by DarkWolfLinux** [comment]
You are best <3
