### ISSUE TITLE
bumblezone mod sugar water bucket duplication glitch

### ISSUE THREAD

**Issue by aurimilky** [The-Nexus-Project/Limitless-5#11]
I found a duplication glitch with the bumblezone mod on ll5 server.

I had 7 buckets of water and I added sugar to them to make sugar water. the 7 x sugar water buckets was crafted and I also got back the 7 x water buckets. instead of having just 7 sugar water buckets and minecraft removing the 7 x water buckets. the duplication glitch I ended up with 14 buckets in total.

I hope you can find this useful for fixing the bug.

many thanks
ashton

**Comment by Gbergz** [comment]
Not sure I can fix this, since it seems to be built in feature to return the bucket. Such a small minor dupe so I doubt it would be a game changer if this stays.
