### ISSUE TITLE
[Issue]: Mekanisms Enrichment Chamber creates unusable dust

### ISSUE THREAD

**Issue by Maximilian754** [The-Nexus-Project/Limitless-5#110]
### What happened?

Putting blocks of raw ore into Mekanisms Enrichment Chamber produces ore dust from Mekanism which is unusable.

### Pack Version

Version: 2.10.0

### To Reproduce

1. Put a block of raw gold, iron, copper ore lead into Mekanisms enrichment chamber
2. Recieve gold, iron, copper ore lead dust from Mekansim

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

**Comment by Gbergz** [comment]
Thanks for the report!

**Comment by Gbergz** [comment]
Will be fixed in the upcoming update.
This issue was recently introduced as Mekanism added Raw Ore Block processing recipes I wasn't aware of.
