### ISSUE TITLE
[Issue]: Twilight Forest Uncrafting Table balance issues

### ISSUE THREAD

**Issue by GoldVinyl** [The-Nexus-Project/Limitless-5#111]
### What happened?

The uncrafting table, which can be obtained from exploring in Twilight Forest, can be used to uncraft items in certain game-breaking ways. For example, 2 gold ingots can be "uncrafted" into 1 gold ingot and a full charge tome of alkahestry, which can then be used to create half a stack more gold, redstone, .etc.

### Pack Version

Version: v2.10.0

### To Reproduce

1. Obtain uncrafting table
2. Uncraft 2 gold ingots
3. Get back 1 gold ingot and a tome of alkahestry. 
4. Use tome to make more gold or other items.

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.

**Comment by Gbergz** [comment]
Normally the recipe for the uncrafting table from twilight is disabled because of this issue. Will add a script that removes it if you acquire it next update.

**Comment by Gbergz** [comment]
Also Uncrafting Tables or similar blocks are just a nightmare in heavy modded.
