### ISSUE TITLE
[Config Tweak] Angel ring 2.0

### ISSUE THREAD

**Issue by RandomCrit** [The-Nexus-Project/Limitless-5#112]
Hi.
Angel Ring was updated to version 2.0 in Limitless 5, but in that version the angel ring cost XP to use.
However , the scroll from enigmatic legacy that is used to craft the angel ring allow for free flight while in a beacon's range and allow flying everywhere else as the cost of xp, turning the angel ring into a downgrade.

The best way to fix it would be to turn off the XP cost of the angel ring in the config file.
There's also new rings costing rf to use, but since you need to first craft the classic angel rings they are worthless, so disabling their recipe would probably be a good idea.

Thanks for the modpack. Have a nice day

**Comment by RandomCrit** [comment]
Honestly just downgrading the mod would be the best way to fix this issue, since even when you disable the xp cost you still need at least 1 level to fly, and if you're using the scroll from enigmatic legacy to store your xp automatically you can't use the angel ring

**Comment by Gbergz** [comment]
Fixed this issue in the newest hotfix.
And even if you still need 1 level, that's not really that hard. Kill one mob.
