### ISSUE TITLE
Thermal Series Lead Dust cannot be smelted or melted

### ISSUE THREAD

**Issue by brandonclyon** [The-Nexus-Project/Limitless-5#114]
### What happened?

Immersive Engineering Lead Ore gives IE Raw Lead, when fed through a Pulverizer turns to Thermal Series Lead Dust. This dust has no use, it cannot be smelted or cooked. 

### Pack Version

2.11.0_hf2

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

**Comment by Gbergz** [comment]
Fixed in v2.11.1!
