### ISSUE TITLE
[Issue]: Advanced beehives are unusable in v2.11.1

### ISSUE THREAD

**Issue by CrossJaw** [The-Nexus-Project/Limitless-5#116]
### What happened?

There is a known issue in version 0.9.0.6 of the Produce Bees mod where vanilla and modded bees cannot enter advanced beehives on servers. This Issue has been acknowledged by the mod developer and has supposedly been fixed in version 0.9.0.7. Further confirmation of this fix may be needed. 

### Pack Version

Version: 2.11.1

### To Reproduce

1. Open a server with version 2.11.1.
2. Place an advanced beehive in a open area.
3. Spawn a vanilla or a bee from the Productive Bees mod.

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [X] No.

### Anything else to add?

Testing for myself, this problem does not seem to be present in singleplayer. This problem has already been acknowledged by the mod developer as well as myself that this seems to be widely a server issue.

**Comment by Gbergz** [comment]
Is this fixed in `v2.12.0`?
