### ISSUE TITLE
Loot chest only have Minecraft and orcz items on server installation

### ISSUE THREAD

**Issue by MysticEntity-dev** [The-Nexus-Project/Limitless-5#117]
I have downloaded the Serverfiles, extracted them. Installed forge server on different folder then copied the forge files into the folder of the downloaded serverfiles. The server start and im able to join but the loot chests are only filled with minecraft and orcz items: 
![image](https://user-images.githubusercontent.com/77643927/177039805-cb57f8fc-274b-48b9-ad28-4f6b8336c94c.png)
![image](https://user-images.githubusercontent.com/77643927/177040071-435d2cdd-48e4-4916-9f9a-c5d47bc8c313.png)
Also the downloaded serverfiles only have 452 mods in the mods folder, i dont know if that is correct or not: 
![image](https://user-images.githubusercontent.com/77643927/177040042-4b91ca61-324d-4cfe-b888-efb3c435b19a.png)

**Comment by Gbergz** [comment]
And how many chests did you actually try? How many different Dungeons, structures? Can't reproduce this.

**Comment by MysticEntity-dev** [comment]
tried at least 20 chests, but after deleting the world folder and restarting its fine now. Sry for the unnecessary issue
