### ISSUE TITLE
[Issue]: Eldrin Flight is a "positive" potion effect despite it having negative effects

### ISSUE THREAD

**Issue by TopPercentageRattata** [The-Nexus-Project/Limitless-5#118]
### What happened?

Corail blessing enchant and Ankh of Prayer can give Mana and Artifice's Eldrin Flight potion effect, which completely locks a player in place and makes them unable to be moved despite being a "positive" potion effect.

### Pack Version

Version: 2.12.0

### To Reproduce

1. Use blessing enchantment on armor or pray with ankh of prayer near a grave a lot of times.
2. Get stuck for a long time
3. Suffer

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [X] Using Rubidium
- [ ] Using Rubidium + Oculus
- [ ] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

**Comment by Gbergz** [comment]
Not sure I can fix this, report to MnA.
