### ISSUE TITLE
[Issue]: Some Bonsai trees give wrong logs

### ISSUE THREAD

**Issue by TopPercentageRattata** [The-Nexus-Project/Limitless-5#119]
### What happened?

Bonsai trees for all Quark Blossom saplings somehow give oak logs instead of the blossom logs that the real trees give.
Additionally, while azalea trees give Ecologics azalea and flowering azalea logs, as bonsai trees they just give oak logs. 

Apparently bonsai tree outputs can be modified via datapack according to the Bonsai Trees 3 github so this can be fixed by doing that hopefully.

### Pack Version

Version: 2.12.0

### To Reproduce

1. Put azalea bush or flowering azalea bush or any quark blossom sapling onto a bonsai pot that has grass
2. Only get oak logs instead of pretty modded wood logs
3. Despair

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [X] Using Rubidium
- [ ] Using Rubidium + Oculus
- [ ] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

**Comment by Gbergz** [comment]
Will get this fixed for the next update.
Thanks for the report.
