### ISSUE TITLE
Using Crafting Terminal 

### ISSUE THREAD

**Issue by anita5552** [The-Nexus-Project/Limitless-5#12]
When using Crafting Terminal I tried to type in @mystical , after the @my it closes the crafting terminal. Bug? So i can never search it in, but manually find it. I did try take out every keybinding that is Y, and still happens.

thanks
![Grison20220116](https://user-images.githubusercontent.com/51015024/149664628-f4b1971f-802a-4c6f-a193-96c27ed87c3c.png)
![Spiketail20220116](https://user-images.githubusercontent.com/51015024/149664629-7c7dcd36-5abb-451f-bb49-ece06416bce3.png)

**Comment by Gbergz** [comment]
Y is the keybind for the mod "FindMe", by default it's on **Y**. It searched for items on containers nearby and highlights them with particles.
Go into controls, check the category button, type "**find**". Unbind it.

**Comment by anita5552** [comment]
I already unbind it
![NitaBillygoat20220116](https://user-images.githubusercontent.com/51015024/149681616-610d90c2-8d83-4ff1-a3b6-c5a7cffc1ff3.png)
.

**Comment by Gbergz** [comment]
Just tested this myself, and after unbinding it the issue is solved. So.. huh..

**Comment by Gbergz** [comment]
Try changing search mode. The buttons top left in the gui.

**Comment by anita5552** [comment]
![NitaHoneybadger20220116](https://user-images.githubusercontent.com/51015024/149682395-d88bdf70-117d-4e3a-bc70-b37ab4d04096.png)

This? i tried all of them everytime i press it

**Comment by anita5552** [comment]
the bottom search bar is fine.. is just the Terminal

**Comment by Gbergz** [comment]
Can't for the love of god reproduce this at all. Just can't.

**Comment by anita5552** [comment]
:( yeah idk? my friend also has the same problem when she search up Hay with the Y

**Comment by Vexalus** [comment]
Try checking what other keys are bound to Y. I believe I had the same issue before and fixed it by unbinding something, but I don't quite remember what it was.

**Comment by Gbergz** [comment]
Well since you've unbinded it it should work. I get the same issue when it is binded to Y.
Just change the keybind to something else instead of unbinding it?

**Comment by anita5552** [comment]
I did, still does the same thing. I have Y on drop selected item. but it shouldnt effect it. I had it on Y ever since i played, it hasnt happen before till now.

**Comment by Gbergz** [comment]
Try re-installing the pack, and if you're using CurseForge. Swap launcher.

**Comment by anita5552** [comment]
uhm but if its curseforge.. it wouldnt be both of us have the same problem?

**Comment by Gbergz** [comment]
Just try reinstalling it.

**Comment by anita5552** [comment]
same thing...

**Comment by Gbergz** [comment]
Try removing the mod.

**Comment by Gbergz** [comment]
Fixed next update.
