### ISSUE TITLE
[Issue]: Opening a storage while being in a discord call freezes the game for varying amounts of time

### ISSUE THREAD

**Issue by iiVeil** [The-Nexus-Project/Limitless-5#120]
### What happened?

When opening storage (inventory, chests, etc.) while in a discord call (we used a server vc), the game freezes for various amounts of time. Seemingly the larger the storage the longer it freezes for, while opening the inventory is a small stutter, opening our occultism storage (~3000 slots) freezes the game entirely, with unchanging memory values in task manager, forcing you to restart it.

### Pack Version

Version: 2.11.1

### To Reproduce

1. Have SimpleDiscordRichPresence Installed (comes with mod pack)
2. Be in a discord call, we used a server VC
3. Open a sufficiently large storage, we used a 3000 slot (ours is filled 2.5k)
4. The game will either freeze, stutter, or crash

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [X] No.

### Relevant log output / crash report.

```shell
No crash log, the game freezes until closed via task manager.
```

### Anything else to add?

Removing the SimpleDiscordRichPresence mod seems to solve this issue. 
This has never been an issue before 7/3/2022 despite no change in version of the modpack (2.11.1 the entire time)

**Comment by Gbergz** [comment]
This is a weird issue.
But I can't reproduce it. At all.
