### ISSUE TITLE
[Issue]:  sophisticated backpacks pickup upgrade

### ISSUE THREAD

**Issue by ninjacoder144** [The-Nexus-Project/Limitless-5#122]
### What happened?

The pick-up upgrade on sophisticated backpacks ignores the filter added to the pick up

### Pack Version

Version: 2.13.0

### To Reproduce

1.

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

**Comment by Gbergz** [comment]
Hey, thanks for report. Just tried this myself in-game and filter works as expected.
