### ISSUE TITLE
[Issue]: Mekasuit HUD doesn't show up

### ISSUE THREAD

**Issue by roma291100** [The-Nexus-Project/Limitless-5#124]
### What happened?

Mekasuit is fully charged. Still no HUD after putting on the mekasuit helmet

### Pack Version

Version: 2.13.0

### To Reproduce

1. Try to put the mekasuit helmet on

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

**Comment by Gbergz** [comment]
If you want the HUD, enable it in the config. It's turned off by default.

**Comment by Gbergz** [comment]
No but you can re enable it while in-game.
