### ISSUE TITLE
[Issue]: Endergenic Cells not working from RFTool | Potentially Unable to Link

### ISSUE THREAD

**Issue by RainyJimbo** [The-Nexus-Project/Limitless-5#125]
### What happened?

I attempted to create a basic Endergenic Setup for a power supply as shown here on a single player world (creative):
https://imgur.com/X6aTfvY

However I had noticed that when selecting the cells to get linked up it, while you will see it says on the chat it seems to have been linked up, there is no indication that it had been selected (normally it will be highlighted)

Thinking it was maybe a bug, I went ahead and completed the setup and gave the pearl injector stacks of pearls but it would just log that the pearl was lost on the top left endergenic leading to the assumption that its not linked correctly.

the setup I used is the most basic of all the guides where the sequencers are set to 3 and 5 respectively on the inside and 1 3 for the 2 outside. 

### Pack Version

Version: 2.11.1

### To Reproduce

1. Place down 4 Endergenic Cells along with the sequencers, ender monitors, timer and pearl injector
2. Right click with Smart Wrench (Wrench Mode) from one endergenic cell to another in a clockwise rotation.
3. Set 4 inner sequencers to 3 and 5 once2
4. Set 2 outer sequencers to 1 and 3 once2
5. Set all ender monitors to pearl fired
6. Set timer to 30 ticks and disable on redstone
7. Insert Pearls to Pearl Injector

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

**Comment by RainyJimbo** [comment]
Hello,

The issue still persists with the latest pack version v2.14.0
![endergenic still not working on latest](https://user-images.githubusercontent.com/53384543/178614984-a0647e6a-ee7e-445f-a05c-e3a0a89e99fd.jpg)

**Comment by Gbergz** [comment]
Report to Rftools and see what they say.
