### ISSUE TITLE
[Issue]: Create Sturdy sheets require powdered obsidian only obtainable through Productive bees 

### ISSUE THREAD

**Issue by jinkhya** [The-Nexus-Project/Limitless-5#126]
### What happened?

Hello, to make sturdy sheets from create you need powdered obsidian from create. It won't accept the mekanism one.
An easy fix would be to change the ingredient to `"tag": "forge:dusts/obsidian"` or to make it use the mekanism obsidian dust =)
I don't think it was intended to gate those with productive bees ^^ The issue is probably just because of the vanilla recipe for those sheets using item name and not tag. 
Thanks in advance !

### Pack Version

Version: 2.14.0

### To Reproduce

1. try making sturdy sheets through sequenced assembly with mekanism dust. 

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

**Comment by Gbergz** [comment]
Thanks for the report.
Will get this sorted for an upcoming update. :)
