### ISSUE TITLE
[Suggestion]: Remove the Orcz mod 

### ISSUE THREAD

**Issue by jinkhya** [The-Nexus-Project/Limitless-5#131]
### What happened?

Hello :)
This is not a bug report but more of a request, can we remove the orcz mod please? They spawn everywhere (I saw the issue about them spawning a lot in Dimensional Dungeon too) They don't really bring anything to the game, they're more of a nuisance than anything and use a lot of the mob cap. 
Thanks for considering it,
Jin

### Pack Version

Version: 2.14.0

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

**Comment by Gbergz** [comment]
I would remove it, but sadly it would break existing worlds and that is something I would like to avoid at all costs.

But I am currently trying to find a way to disable the spawning of them without removing the mod fully.

I will update here if I do find a way.
