### ISSUE TITLE
Recipe missing for Aluminium Plate in Thermal's Multiservo Press 

### ISSUE THREAD

**Issue by Flachdachs** [The-Nexus-Project/Limitless-5#132]
All other plates from Immersive Engineering (and other mods) can be created in Thermal's Multiservo Press but Aluminium Plate can't. Is this intended?

**Comment by Flachdachs** [comment]
Just tested it in 2.15.0. Still missing.

**Comment by Gbergz** [comment]
Will release a .1 update soon which will fix this.

**Comment by Gbergz** [comment]
fixed in 2.15.1
