### ISSUE TITLE
[Issue]: Quest Beekeeper's Suit in the Thermal Series page

### ISSUE THREAD

**Issue by Flachdachs** [The-Nexus-Project/Limitless-5#133]
### What happened?

This quest can't be completed except by chance from Loot Bags. There are no recipes for the parts and also the Woven Fabric used to build the parts is missing. These items are part of Thermal Cultivation which is not included in this mod pack.

### Pack Version

Version: 2.15.0

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [ ] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [ ] No.

**Comment by Gbergz** [comment]
Thanks for the report!

This is an oversight on my part, really. The quests were moved from LL3 to LL5 and Cultivation was part of that mod. 
Will get this sorted for a future update. :)

**Comment by Gbergz** [comment]
fixed in the upcoming update. ( v2.16.0 ).
