### ISSUE TITLE
[Issue]: 

### ISSUE THREAD

**Issue by T1MMY301** [The-Nexus-Project/Limitless-5#135]
### FTB Chunk loading not working

Chunk loading with FTBChunks does not work anymore. Lava pumps in the nether do not continue to pump once returning to overworld, along with fission reactors not working a few chunks away even though they are supposed to be loaded in FTB Chunks.

### Pack Version

Version: 

### To Reproduce

1.

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [ ] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

**Comment by Gbergz** [comment]
Hey, thanks for report.

But I tried. It works. Can't reproduc your issue.

Also you forgot title. version, and other check boxes.
