### ISSUE TITLE
non existent Pigs

### ISSUE THREAD

**Issue by Mas3nko** [The-Nexus-Project/Limitless-5#136]
Updated from v2.14.0 to v2.15.0 and basically my pigs are gone. decided to go into a creative and use spawn eggs to spawn pigs; however, they never spawned. I also tried cows and they spawn so the only thing is pigs not spawning.

**Comment by Gbergz** [comment]
Thanks for the report!

Will investigate.

**Comment by Gbergz** [comment]
Will release a .1 update soon which will fix this.

**Comment by Mas3nko** [comment]
That is what is up, thanks for the quick response.
