### ISSUE TITLE
[Issue]: Quest Repurposed Structures - small description errors

### ISSUE THREAD

**Issue by Flachdachs** [The-Nexus-Project/Limitless-5#138]
### What happened?

- Quest "Tomb Raiding" description says "Find all 14 Temples" but there are only 5.
- Quest "View from Above" description says "Find all 14 Outposts" but there are only 13.

### Pack Version

Version: 2.15.0

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [ ] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [ ] No.

**Comment by Gbergz** [comment]
thanks, minor issue.
will fix sometime!

**Comment by Gbergz** [comment]
fixed in the upcoming update ( v2.16.0 ).
