### ISSUE TITLE
[Issue]: Elementalcraft pure ore chunk

### ISSUE THREAD

**Issue by Mas3nko** [The-Nexus-Project/Limitless-5#142]
### What happened?

hello, I'm having an issue with elemental craft pure ore chunks. you can't smelt the chunks of both vanilla and modded resources. went to a creative world and tried to smelt them on a regular furnace and a blast furnace and there was still nothing. This happened with version 2.15.1, but I have a profile with version 2.14.0 so, I launched that version to see if was an issue from 2.14 to 2.15.1; however, the issue was still happening in 2.14.

### Pack Version

Version: 

### To Reproduce

1.

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

### Anything else to add?

the ore purifier works fine, it just the chunks cant be smelted in any kind of furnace.

**Comment by Gbergz** [comment]
Not quite sure how to fix this, but I'll have this opened for maybe a future update where I'll look into it further.
