### ISSUE TITLE
[Issue]: Create Trains carriages stuck when outside of screen

### ISSUE THREAD

**Issue by Roncarlos** [The-Nexus-Project/Limitless-5#143]
### What happened?

Carriages of Trains (Create mod) stay stucked when outside of screen.

Seems related to: https://github.com/Creators-of-Create/Create/issues/3195

The windmill is glitching as well, maybe that's the same bug!

### Pack Version

Version: 2.15.1

### To Reproduce

1. Create a train with a carriage
2. Run it with a npc
3. Don't look at the train while it is moiving
4. Look back at the carriage it should be stuck and disappear

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [x] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

### Anything else to add?

Fixable by addind to entity culling json file, to entityWhitelist: "create:carriage_contraption"
(Tested)

**Comment by Gbergz** [comment]
I'll add that culling entry for next update.

**Comment by Roncarlos** [comment]
Has been done in 2.17.1
