### ISSUE TITLE
[Issue]: Quest greedy familiar from occultism not working

### ISSUE THREAD

**Issue by Roncarlos** [The-Nexus-Project/Limitless-5#149]
### What happened?

I spawn the familiar but the quest don't validate.

![image](https://user-images.githubusercontent.com/9269672/182459180-3d2f6ec7-85cf-4553-9fef-a273f9bac60d.png)

![image](https://user-images.githubusercontent.com/9269672/182459224-6d6030b1-73b7-40e0-b76e-bbde2d6ff04b.png)

### Pack Version

Version: 2.16

### To Reproduce

Do all the required quests then try to summon

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

**Comment by Gbergz** [comment]
Hello, I can't reproduce this issue, the quest completes fine. Are you sure you're doing it correctly?

**Comment by Roncarlos** [comment]
I think i did all the step correctly. Or am i missing something?
![image](https://user-images.githubusercontent.com/9269672/182717905-ce1fe48e-43dd-4b3a-a8d0-6438d295f8a2.png)

**Comment by MiriamAlter** [comment]
This applies to the other familiar quests as well.

**Comment by Gbergz** [comment]
This is known, however not sure if it can be fixed, it triggers correctly for me. But that is if the advancement the quest is based on is given through commands. Not doing it normally.
