### ISSUE TITLE
NA Server Crashing

### ISSUE THREAD

**Issue by Mckaddict14** [The-Nexus-Project/Limitless-5#15]
The NA servers are lagging people out, me and a buddy have both been booted more than once since getting on this morning

**Comment by Gbergz** [comment]
Wrong place for this.

**Comment by Mckaddict14** [comment]
> Wrong place for this.

Where should this be reported then if not the issue reporting tool?

**Comment by Gbergz** [comment]
The discord, this is for pack specific issues, not a server.

**Comment by Mckaddict14** [comment]
Ok.. Tried there to and didn't get any answer that's why I tried here too.
