### ISSUE TITLE
[Issue]: Mechanical Saw from Create three recipes with same items

### ISSUE THREAD

**Issue by Roncarlos** [The-Nexus-Project/Limitless-5#150]
### What happened?

The mechanical saw from Create mod have three recipes that have the same items (it then round robin between each recipe, thus needing 3 log for 1 stripped log when automating).
![image](https://user-images.githubusercontent.com/9269672/182659404-e0e6cdd4-a60b-476e-aa89-0d1b60a8cd94.png)
![image](https://user-images.githubusercontent.com/9269672/182659574-1d1491e0-6798-4adf-8e65-6c28c85010cc.png)

I think for create we should only have the first recipe and not the others for mechanical saw.

### Pack Version

Version: 2.16

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

**Comment by PhantomEnderium** [comment]
Smart that it round robins the recipes, but I do agree it shouldn't be a thing for create based machines, unless there was a way to pick which recipe got made.

**Comment by RandomCrit** [comment]
you can put a filter on mechanical saws, so it will only do the recipe it was set to.

**Comment by Roncarlos** [comment]
![image](https://user-images.githubusercontent.com/9269672/182714581-0606d3e0-6520-4e99-b6af-7b19720f4809.png)
Indeed my bad

**Comment by Roncarlos** [comment]
Of i'm reopening this because if you want to automate log stripping, using the recipe is not a solution. You'll need 1 saw for each log. I don't think it's right.

**Comment by RandomCrit** [comment]
can't you use an atribute filter with a tag that prevent the second item from being crafted?

**Comment by Roncarlos** [comment]
Right it works, my bad.
