### ISSUE TITLE
[Issue]: irongenerators not dropping with silent gear picks

### ISSUE THREAD

**Issue by Mechantronic** [The-Nexus-Project/Limitless-5#153]
### What happened?

while trying to replace a generator from iron generators (tried stone and gold), while using a silent gear pickaxe and paxel. the item did not drop. When i grabbed a diamond vanilla pick it did drop

### Pack Version

Version: V2.16.0

### To Reproduce

1.get a generator from iron generators.
2.get a pickaxe/paxel from silent gear
3. place the generator
4. destroy the generator with the silent gear pickaxe/paxel

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

**Comment by RandomCrit** [comment]
They don't drop while using tetra's tool either

**Comment by Gbergz** [comment]
This issue is on Iron Generators, and has already been reported on their CurseForge comment page.

Thanks for report anyways!
