### ISSUE TITLE
[Issue]: Wood Jetpack quest of Iron Jetpacks not working

### ISSUE THREAD

**Issue by Simmesh** [The-Nexus-Project/Limitless-5#154]
### What happened?

I crafted two Wood Jetpacks but the quest did not finish.

### Pack Version

Version: 2.17.1

### To Reproduce

1.

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

**Comment by Gbergz** [comment]
Read the Quests, the readme one.
