### ISSUE TITLE
Copshowium not being produced in Imbuer[Issue]: 

### ISSUE THREAD

**Issue by Kickn911** [The-Nexus-Project/Limitless-5#156]
### What happened?

When i use the Copshowium Imbuer in TNP Limitless 5 when i apply a time beam the Imbuer empties but nothing come out. FYi using Molten Copper from Tinkers. i also contacted the mod creator and has verified that it does work on the version in this mod.

### Pack Version

Version: 1.17.1

### To Reproduce

1. Fill Imbuer with Tinkers Molten Copper
2. Using Charcoal and Gunpowder produce time beam into imbuer

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [X] Using Rubidium
- [ ] Using Rubidium + Oculus
- [ ] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

**Comment by Gbergz** [comment]
Thanks for report.
I will investigate this.
