### ISSUE TITLE
[Issue]: Server Crash due to mining gadgets

### ISSUE THREAD

**Issue by Roncarlos** [The-Nexus-Project/Limitless-5#157]
### What happened?

My friend was mining with the mining gadget with almost all upgrades. And the server crashed

Crash Report:
[crash-2022-08-07_12.34.00-server.txt](https://github.com/The-Nexus-Project/Limitless-5/files/9276798/crash-2022-08-07_12.34.00-server.txt)
.

### Pack Version

Version: 2.17.1

### To Reproduce

1.

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [X] Using Rubidium + Oculus
- [ ] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

**Comment by Gbergz** [comment]
You can probably almost be certain this is caused by Oculus, try without it.

**Comment by Roncarlos** [comment]
It's not a client crash, but a server one.

**Comment by Gbergz** [comment]
https://github.com/Direwolf20-MC/MiningGadgets/issues
