### ISSUE TITLE
[Issue]: Enchanting Infuser Enchanting Power

### ISSUE THREAD

**Issue by Greyman131** [The-Nexus-Project/Limitless-5#158]
### What happened?

Enchanting Infuser Enchanting Power is stuck at 15
![2022-08-09_14 01 34](https://user-images.githubusercontent.com/111013329/184001519-05097c54-be9a-4ffa-b208-6084355bb8f1.png)
![2022-08-09_14 01 43](https://user-images.githubusercontent.com/111013329/184001538-bb2ca0eb-7df4-469a-ad3d-70d74bbc1950.png)
 

### Pack Version

Version: v2.17.1

### To Reproduce

1.

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [X] Using Rubidium + Oculus
- [ ] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

**Comment by Gbergz** [comment]
Hey, thanks for report! :)
But this is not an issue, you need to use apotheosis bookshelves to get above 15.
