### ISSUE TITLE
[Issue]: Loot Bag dropping an invalid item.

### ISSUE THREAD

**Issue by ThiccBoy69** [The-Nexus-Project/Limitless-5#159]
### What happened?

The lootbag gave me an air conditioning upgrade from pneumaticcraft, which is not ubtainable without the corresponding mod (not present in the modpack)

### Pack Version

Version: 2.17.1

### To Reproduce

1. click a lootbag and hope it gives you the thing ?!?!?!?

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [X] Using Rubidium + Oculus
- [ ] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

**Comment by PhantomEnderium** [comment]
Gbergz would it be possible to make a new thread dedicated to "illegal" loot bag items?

**Comment by Gbergz** [comment]
Late reply, but the item ID for this item would be lovely.
