### ISSUE TITLE
[Issue]: 

### ISSUE THREAD

**Issue by BlackTiger007** [The-Nexus-Project/Limitless-5#160]
### What happened?

[Error](https://bytebin.lucko.me/3HqRfh8w4E)
![image](https://user-images.githubusercontent.com/66371975/184544147-6408e352-9fb6-40f1-aa05-06ce428b89b5.png)

### Pack Version

Version: 2.18.0

### To Reproduce

1.EU2 Joinen

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [x] No. None of them. Unmodified.

### Are you on a Server?

- [x] Yes.
- [ ] No.

### Relevant log output / crash report.

```shell
https://bytebin.lucko.me/pe4EuUFeRm
```

**Comment by Gbergz** [comment]
Reinstall modpack

**Comment by Gbergz** [comment]
Continue discuss official server issues in our discord.
