### ISSUE TITLE
[Suggestion]: Add asupport for all seeds from mystical agriculture to thermal phytogenic insulator

### ISSUE THREAD

**Issue by Roncarlos** [The-Nexus-Project/Limitless-5#161]
### What happened?

Would be nice to have all seeds from mystical agriculture works with phytogenic insulator. 
The cloche from immersive enginnering already supports it.

### Pack Version

Version: 2.18

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [ ] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [ ] No.

**Comment by Gbergz** [comment]
Maybe in the future, I will write this in my todo list.
Thanks for the suggestion.
