### ISSUE TITLE
[Issue]: crash

### ISSUE THREAD

**Issue by XDDX12311** [The-Nexus-Project/Limitless-5#163]
### What happened?

A bug happened! i placed on ground venus globe and my world instantly crashed .
on secend world hapend the same

### Pack Version

Version: 1,18,2

### To Reproduce

1.put venus globe on ground 

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [ ] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [ ] No.

### Relevant log output / crash report.

```shell
ed976f09-83f6-4d5c-9b6d-62fc4cbb4f46
```

**Comment by Gbergz** [comment]
didn't click on anything, no logs , please open a new issue with new info.
