### ISSUE TITLE
[Issue]: Dupe with Item user, logistical sorter and stable wormhole

### ISSUE THREAD

**Issue by sprocketaudio** [The-Nexus-Project/Limitless-5#164]
### What happened?

Was attempting to create an auto feeder for the Energizer orb from Powah mod. Used a logistical sorter, Item user, and Stable wormhole. 
the intent was to feed in Uranium ingots to convert to Uraninite. When activated, the User began spewing out stacks of Uraninite without consuming any uranium or very little
While attempting to dismantle, i removed each piece 1 by 1 and it still continued until the User was removed as the last component
the output also was not hooked up to any storage device but the orb seemed to sometimes process the uranium but the uraninite would just disappear completely.
![image](https://user-images.githubusercontent.com/13222732/185093144-5b8c4efb-0ccc-4a5d-a3f2-c7f9dbe0f917.png)
![image](https://user-images.githubusercontent.com/13222732/185093158-21e905ae-d50c-425c-bbd4-931ae1fdcb45.png)
![image](https://user-images.githubusercontent.com/13222732/185093181-20c02544-35de-4f28-a9a0-2966fc01941a.png)
![image](https://user-images.githubusercontent.com/13222732/185093204-119f1ea6-1a7b-4805-9b21-f2a510707eaf.png)

### Pack Version

Version: 2.17.1

### To Reproduce

1.

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

**Comment by Gbergz** [comment]
Thanks for report, but I am not sure that I can fix this myself.
