### ISSUE TITLE
[Issue]: Dupe with Cyclic Sack of Holding and Bonsai Trees 3 Bonsai Pot.

### ISSUE THREAD

**Issue by TheOneTrueDev** [The-Nexus-Project/Limitless-5#165]
### What happened?

When picking up bonsai pot with the sack of holding the user is able to try to place it down but it says there's an error and nothing is placed but any items that were inside the bonsai pot will be spawned on the ground. It looks like the bag disappears but it doesn't allowing the player to spam dupe any item.

### Pack Version

Version: 2.18.0

### To Reproduce

1. Grab Cyclic Sack of Holding
2. Place item to be duped inside a bonsai pot from Bonsai Pots 3
3. Pick up bonsai pot with the sack
4. Attempt to place the bonsai pot
5. Profit

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

### Relevant log output / crash report.

```shell
N/A
```

### Anything else to add?

OP pls fix! jk thanks for taking the time to read this though! <3

**Comment by Gbergz** [comment]
Can you report this to Cyclic and see what they say aswell?

**Comment by TheOneTrueDev** [comment]
Left a report but haven't seen anything back yet.
https://github.com/Lothrazar/Cyclic/issues/2162
