### ISSUE TITLE
[Issue]: Some machines doesn't show what it can do in jei

### ISSUE THREAD

**Issue by ZeroXion** [The-Nexus-Project/Limitless-5#166]
### What happened?

some machines doesn't show what it can do in jei
ie. machines from integrated dynamic   squeezerer  and drying basin

### Pack Version

Version: 2.18.1

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

**Comment by Gbergz** [comment]
Hey! Thanks for report.
This isn't on us, it's just that some mods have probably dropped support for JEI 9 and moved over to JEI 10.
Recipes still work, some just doesnt show up.
