### ISSUE TITLE
[Issue]: Error: could not open `libraries/net/minecraftforge/forge/1.18.2-40.1.73/unix_args.txt'

### ISSUE THREAD

**Issue by cl500** [The-Nexus-Project/Limitless-5#167]
### What happened?

I updated my server and now I get this error

### Pack Version

Version: v2.18.2

### To Reproduce

1. I Replaced every single file I had to replace in order to update the server (as usual, it´s my third time updating this server) and now all I get is this error.

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

### Relevant log output / crash report.

```shell
Error: could not open `libraries/net/minecraftforge/forge/1.18.2-40.1.73/unix_args.txt'
```

**Comment by cl500** [comment]
Updated Java but I still get the same error

**Comment by Gbergz** [comment]
It is caused by Java, then you don't have it as the primary Java.

**Comment by cl500** [comment]
https://i.imgur.com/0CD6abf.png
https://i.imgur.com/Lzt2Hoi.png
am i stupid? probably yes.

**Comment by Gbergz** [comment]
Try restarting your pc.
