### ISSUE TITLE
[Issue]: Server Can't Keep Up!

### ISSUE THREAD

**Issue by PhantomEnderium** [The-Nexus-Project/Limitless-5#169]
### What happened?

Server freezes a lot in terms of the world "stopping" due to overloading. Happens every minute or so. Log is spammed with whats shown below

### Pack Version

Version: 2.18.2

### To Reproduce

1. Launch server, watch log

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [X] Using Rubidium
- [ ] Using Rubidium + Oculus
- [ ] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

### Relevant log output / crash report.

```shell
[po.by.BYG]: 7578 biome parameter points were mapped for BYG region: byg:region_0
[po.by.BYG]: 7578 biome parameter points were mapped for BYG region: byg:region_1
[po.by.BYG]: 7578 biome parameter points were mapped for BYG region: byg:region_2
[po.by.BYG]: 7578 biome parameter points were mapped for BYG region: byg:region_3

[minecraft/MinecraftServer]: Can't keep up! Is the server overloaded? Running 6956ms or 139 ticks behind
```

### Anything else to add?

Anyway to fix this or disable BYG doing this, assuming thats the cause? This server is like, brand new, with 12gb ram out of 32 used. No bottlenecks.

Sorry for double spamming github, pc decided to send first one early

**Comment by Gbergz** [comment]
This message is completely normal and causes no harm. Its a logging thing to tell you that BYG biomes generate in the world.

It can't be turned off.

**Comment by PhantomEnderium** [comment]
> This message is completely normal and causes no harm. Its a logging thing to tell you that BYG biomes generate in the world.
> 
> It can't be turned off.

Damn okay. Any reason why it cant keep up then?

**Comment by Gbergz** [comment]
Doing anything specific? 
Just generating the world will make it "can't keep up" which is also normal.

**Comment by PhantomEnderium** [comment]
> Doing anything specific? Just generating the world will make it "can't keep up" which is also normal.

No, nothing. No machines yet. Pregened a ton as well beforehand

**Comment by Gbergz** [comment]
Not sure then. Run a profiler with spark for some minutes.
/spark profiler
then
/spark profiler --stop

**Comment by PhantomEnderium** [comment]
> Not sure then. Run a profiler with spark for some minutes. /spark profiler then /spark profiler --stop

[Ran for 20 Minutes](https://spark.lucko.me/ORiZGeIw8c)

**Comment by PhantomEnderium** [comment]
Would also like to mention, it seems to be a consistent 5 minute interval of when it happens, which is really weird

**Comment by Gbergz** [comment]
Discussion transfered to discord, closing.
