### ISSUE TITLE
[Issue]: Ore Miner Djinni durability

### ISSUE THREAD

**Issue by trackfire** [The-Nexus-Project/Limitless-5#170]
### What happened?

Ore Miner Djinni doesn't have increased durability like the quest book says. It has the regular 400 durability even after losing 1 point.

### Pack Version

Version: 2.18.2

### To Reproduce

1. Place Ore Miner Dijnni inside the Dimensional Mineshaft and wait for the durability to drop once

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

**Comment by Gbergz** [comment]
Might just be a mistake in the quest book.
