### ISSUE TITLE
[Issue]: FTBIC Carbon Armor and Quantum Armor auto-swaps with other armor

### ISSUE THREAD

**Issue by adkinss** [The-Nexus-Project/Limitless-5#171]
### What happened?

If wearing FTB Industrial Contraptions' Carbon Armor or Quantum Armor, picking up loot containing armor will be auto-swapped and equipped when that armor goes into your inventory (but not in your hot bar).  

This is actually an interaction with the Inventory Profiles Next mod.  It as auto-refill settings enabled that auto-swaps armor and tools when durability gets down to 2.  This isn't usually an issue, but Carbon Armor and Quantum Armor are always set to a durability of 1, which is below that threshold and triggers the auto-refill capability.

### Pack Version

Version: 2.17.1

### To Reproduce

1. Equip a full set of either Carbon Armor or Quantum Armor. 
2. Pull out a random piece of armor, such as a helmet, and put it in your inventory.  Make sure it has at least 2 durability.
3. The armor should instantly swap with an equipped piece of armor.

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [ ] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

### Anything else to add?

This is a client-only issue and I was able to resolve it by modifying the config settings on the client to blacklist both sets of armor:
-  Mod Config -> Inventory Profiles Next -> Config -> Auto Refill
- Blacklisted item types: `ftbic:carbon_helmet,ftbic:carbon_chestplate,ftbic:carbon_leggings,ftbic:carbon_boots,ftbic:quantum_helmet,ftbic:quantum_chestplate,ftbic:quantum_leggings,ftbic:quantum_boots`

The corresponding client file is `config/inventoryprofilesnext/inventoryprofiles.json`:
>"autorefill_blacklist": "ftbic:carbon_helmet,ftbic:carbon_chestplate,ftbic:carbon_leggings,ftbic:carbon_boots,ftbic:quantum_helmet,ftbic:quantum_chestplate,ftbic:quantum_leggings,ftbic:quantum_boots"

**Comment by Gbergz** [comment]
I'll turn off the Armor Auto refill option for next update.

Thanks for report!
