### ISSUE TITLE
Tin Oreberry not compatible with Create mechanical press

### ISSUE THREAD

**Issue by GPrats360** [The-Nexus-Project/Limitless-5#172]
As stated in the title the Tin Oreberry not compatible with the Create mechanical press, while all the other ore-berries are. Seems it fell through the cracks, or is this intentional?

**Comment by Gbergz** [comment]
Not intentional, caused by an invalid json file, will get it sorted next update.

**Comment by GPrats360** [comment]
Thanks, ill just stockpile them for now untill its fixed then run it through my system.
