### ISSUE TITLE
Forge tag - diet:fruits making many campfire and furnace recipes unobtainable

### ISSUE THREAD

**Issue by stevojhall** [The-Nexus-Project/Limitless-5#175]
### What happened?

Forge tag diet:fruits is adding more food items to raisins, dryed nuts and cooked joshua fruits recipes even if they have their own out pout, example apple -> cooked apple becomes apple -> raisins.

### Pack Version

Version: Minecraft 1.18.2,  
              Forge 40.1.73,
              TNP 5: 2.19.0

### To Reproduce

1. cook apple in campfire or furnace
2. take output
3. see that it is not what was expected

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [X] Using Rubidium + Oculus
- [ ] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

**Comment by Gbergz** [comment]
Can you try without Rubidium and Oculus?

**Comment by Gbergz** [comment]
Nevermind, issue confirmed.

Can you try to downgrade Croptopia to version 2.0.5?

**Comment by stevojhall** [comment]
Croptopia 2.0.5 showing the same recipes. its not a big issue unless you want all the foods for hearts, i can work around this by removing campfire and furnace recipes for say apples except the food i want. There is enough other items to make the other items, if not i can make it say campfire outputs 1 item and furnace another.

I originally tried removing the fruit line for apples in  kubejs/server_scripts/tags_added_removed_items.js

I just thought i would report it as a potential bug

**Comment by Gbergz** [comment]
Okay after some investigating I think I've found the mod causing that issue. Pam's HarvestCraft 2 Food Core.

Can you try to downgrade that instead?
To version 1.0.1, specifically.

**Comment by stevojhall** [comment]
Sorry for the delay, downgrading Pam's to 1.0.1 worked

**Comment by Gbergz** [comment]
Sweet. Will get a .1 hotfix update out soon!

**Comment by Gbergz** [comment]
Should be fixed in [v2.19.1](https://www.curseforge.com/minecraft/modpacks/tnp-limitless-5/files/3960232) as Pam's has been downgraded.
