### ISSUE TITLE
[Issue]: Goblin Trader still spawns when No Soliciting Sign is present

### ISSUE THREAD

**Issue by adkinss** [The-Nexus-Project/Limitless-5#176]
### What happened?

The No Soliciting Sign from @NoMoWanderer only prevents the Wandering Trader and Plague Doctor from spawning within the sign radius.  The Goblin Trader should be prevented from spawning as well.

### Pack Version

Version: 2.19.0

### To Reproduce

1.Be underground or in a basement of a base
2.Place a No Soliciting Sign
3.And wait

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

### Anything else to add?

The nomowanderer-common.toml file has an entityBlockList list that should include goblintraders:goblin_trader.

**Comment by Gbergz** [comment]
This isn't I can control you would have to request this to the mod author.

**Comment by adkinss** [comment]
Are you sure?  The mod explicitly states entities can be added to the config to be blocked from spawning.  I will add it to my local server and see if it works.  If it does not, I will post an issue on NoMoWanderer's mod to see if we can get it fixed.

**Comment by Gbergz** [comment]
If that last part is actually a feature, then it must've been added in a version I've totally missed.

**Comment by adkinss** [comment]
So far so good on the Goblin Trader.  Then, for the first time since I started playing on the server, a Red Merchant is now appearing in my base.  He deals in fireworks and other explosives.  Can we also add supplementaries:red_merchant to the list?

**Comment by Gbergz** [comment]
Initial issue has been "resolved" in [v2.19.1](https://www.curseforge.com/minecraft/modpacks/tnp-limitless-5/files/3960232), enjoy.
