### ISSUE TITLE
[Issue]: levitating 2 glitches out 

### ISSUE THREAD

**Issue by Evilteen18** [The-Nexus-Project/Limitless-5#178]
### What happened?

A bug happened! mobs that can hit you with levitating glitches you out and dont run out and your levitating forever annoying is there anyways to fix it dont like perment levitating 2 and dont want to cvarry milk everytime

### Pack Version

Version: it ben in the old updates and the new one

### To Reproduce

1.get attack by mopbs with levitating 2 and get hit alot of time within a few secs

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [ ] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

**Comment by Gbergz** [comment]
This has been reported over a year ago, and i've still got no clue what causes it. 

But thanks for the report !
