### ISSUE TITLE
Crash after new 2.19.1 install

### ISSUE THREAD

**Issue by CubicalDisaster** [The-Nexus-Project/Limitless-5#179]
### What happened?

A bug happened!

### Pack Version

Version: 

### To Reproduce

1.

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [ ] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [ ] No.

**Comment by Gbergz** [comment]
Open up a new issue with more info.
