### ISSUE TITLE
[Issue]: Zinc Seeds (Mystical Agriculture) missing from JEI

### ISSUE THREAD

**Issue by toqueteos** [The-Nexus-Project/Limitless-5#181]
### What happened?

No zinc seeds appear in JEI (Agricraft or Mystical Agriculture).

![image](https://user-images.githubusercontent.com/699969/188414685-23c79c16-585c-4a3a-8f8d-25c911ce564e.png)

### Pack Version

Version: v2.19.1

### To Reproduce

1. Type 'zinc seed' into JEI search bar
2. No results

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

### Anything else to add?

Instead, if you search usages of zinc ingot and go to the Infusion Altar tab you'll see the recipe it's there (and it works just fine).
![image](https://user-images.githubusercontent.com/699969/188414977-57536831-a1c5-41b9-bb81-03c3b4e0e49e.png)

**Comment by Gbergz** [comment]
Probably just accidentally hidden it.
Will fix.

**Comment by Gbergz** [comment]
Should be resolved in 2.20.0
https://www.curseforge.com/minecraft/modpacks/tnp-limitless-5/files/3969780
