### ISSUE TITLE
[Issue]: TNP Limitless 5 freezes when pausing and saving chunks

### ISSUE THREAD

**Issue by Vulpesq** [The-Nexus-Project/Limitless-5#183]
### What happened?

When playing in singleplayer, pausing causes the game to be frozen.

Personal Log: https://gist.github.com/Vulpesq/bfa67118b4c4e78f0ab197c9587d1135

### Pack Version

Version: 2.20.1

### To Reproduce

1. End a Session, closing the pack
2. Re-launch and re-enter a world
3. Pause the game
4. Freezes 

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [x] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [ ] No.

### Anything else to add?

Log excxeded maxium character length

**Comment by Gbergz** [comment]
Update to 2.20.2
