### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by cauliflower69** [The-Nexus-Project/Limitless-5#186]
What happened?
We started a server and as a certain player loaded a new chunk the server would crash loop

Pack Version
Version: 2.20.2

To Reproduce
Explore terrain generation until something similar happens?

Are you using OptiFine, Rubidium, or Oculus? None

Are you on a Server? Yes.

Relevant log output / crash report.
https://pastebin.com/KKAHxKkz

**Comment by Gbergz** [comment]
Caused by a RopeKnotBlock from Supplementaries.

I would guess a structure from the IDAS mod had this block in its structure, and for some reason causes a crash.

**Comment by cauliflower69** [comment]
I have reported it to the Supplementaries mod dev. Hopefully they find the issue. Thanks for the reply
