### ISSUE TITLE
[Issue]: Joining / Making a world freezes the game

### ISSUE THREAD

**Issue by ILikeProgramming101** [The-Nexus-Project/Limitless-5#187]
### What happened?

Making / Joining a world in the 2.20.2 update freezes my game

### Pack Version

Version:  2.20.2

### To Reproduce

1. Start game
2. Go to singleplayer
3. Make or Join a world

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

### Relevant log output / crash report.

[latest.log](https://github.com/The-Nexus-Project/Limitless-5/files/9547527/latest.log)

**Comment by Gbergz** [comment]
...logs?

**Comment by ILikeProgramming101** [comment]
> ...logs?

All of them?

**Comment by ILikeProgramming101** [comment]
> ...logs?

I added them

**Comment by Gbergz** [comment]
Try reinstalling the pack and try a different launcher like the ATLauncher: https://atlauncher.com/downloads

**Comment by ILikeProgramming101** [comment]
> Try reinstalling the pack and try a different launcher like the ATLauncher: https://atlauncher.com/downloads

Tried re-installing the modpack and tried ATLauncher. Both didnt work

**Comment by Gbergz** [comment]
Don't know why then, sorry. Can't reproduce your issue.

**Comment by ILikeProgramming101** [comment]
> Don't know why then, sorry. Can't reproduce your issue.
> 
> You could I guess restart your system, pc.

Awh, ok!

**Comment by jkneuf** [comment]
I'm having the same problem with pack version 2.21.1 (and 2.21.0). My world that I started many pack versions ago won't load in the newest pack versions. The client just keeps "loading" forever (6 hours overnight). 

I started with the pack on the CurseForge launcher (garbage). Moved to GDLauncher (worked well until latest pack updates, the client says "Not Responding" for hours). So tried it in the ATLauncher, moved old save files to the correct path, and got the same result, "Not Responding" for hours. 

I then created a new world and it worked. Closed that new world to see if something needed to be primed for the old world to work. Launched the old world and it...crashed. The log says it created a crash report, but it didn't. There is no "crash-reports" folder or log.

I have rebooted my computer many times already.

[latest.log](https://github.com/The-Nexus-Project/Limitless-5/files/9584149/latest.log)

**Comment by Gbergz** [comment]
Sorry, but I still can't reproduce the issue. I tried with the OP, lots. Nothing. 
Haven't had an issue loading new pack versions at all on servers. 🤔 💭 

But by looking at that newest latest.log, some config file can't be read, leading to infinite loading time.

**Comment by Gbergz** [comment]
Try stopping server then removing the serverconfigs for easymagic & enchantinginfuser in your world folder.

\world\serverconfig\easymagic-server.toml"
\world\serverconfig\enchantinginfuser-server.toml"

Remove them, then start server.

**Comment by jkneuf** [comment]
That didn't work either. Those two configs just recreated themselves. I'm going to just delete all the config files as there are some in the folder that are old. Will report back...

**Comment by Gbergz** [comment]
Don't delete all config files, pack won't work correctly if you do.
There's just something with your instance / server pretty sure. I can't access files.

**Comment by jkneuf** [comment]
I deleted all the server configs and the world loaded.

**Comment by Gbergz** [comment]
Sweet, I will probably regenerate most serverconfigs next update to prevent this.
And re edit them to the ones they need to be.

**Comment by Gbergz** [comment]
You will now however miss out on lots of serverconfigs that needs to be there for the pack to work properly, you will have duplicate ores, wrong settings for most mods, diet not configured correctly, curios, angel ring, ultimine, ftbchunks etc etc. List goes on.

**Comment by jkneuf** [comment]
I'm a bit confused by the above statement. It seems like the files in the serverconfig folder aren't generated until a world is created since that folder is within the specific world folder within the "saves" folder. It also seems like they are re-created if deleted and the world is started again. After deletion, there are again 112 files in the serverconfig folder, plus a "ftbranks" folder with three files in it.

**Comment by Gbergz** [comment]
I thought you actually meant deleting the "defaultconfig" folder which I use to override serverconfigs on new world join / new world.

You just meant you deleted the serverconfig folder and rebooted, which worked?

**Comment by jkneuf** [comment]
Nope, you never mentioned the 'defaultconfig' folder before, so I didn't mess with it. You only mentioned the \world\serverconfig\ folder. I deleted all the stuff out of that folder, restarted and it worked.

**Comment by Gbergz** [comment]
Sweet. I've got too much to keep track of today, all over the place. :P

**Comment by jkneuf** [comment]
Thanks for your help. Great work by the way. I'm enjoying this pack. There is A LOT of stuff to mess around with.
