### ISSUE TITLE
[Issue]: AgriCraft Crossbreeding not showing in JEI

### ISSUE THREAD

**Issue by KaiusWolf** [The-Nexus-Project/Limitless-5#188]
### What happened?

The Crossbreed section for AgriCraft seeds in JEI had disappeared for me. It was working fine yesterday as I worked towards the diamond flowers, but today it has completely disappeared. Pressing R or left clicking on the JEI window on AgriCraft seeds does not being up the crossbreed recipe, and pressing U or right clicking does not show the crossbreed tab in the list of crafting/uses dispayed

### Pack Version

Version: 2.20.0

### To Reproduce

1. Open Inventory
2. Search for any AgriCraft seed in JEI
3. Press R or left click with recipe mode enabled
4. Nothing will happen

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [x] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

### Anything else to add?

The issue was not present yesterday so I have no idea what has changed between then and now.

**Comment by Gbergz** [comment]
This is not on us, most likely a mod issue.
