### ISSUE TITLE
[Issue]: Levitation never stops

### ISSUE THREAD

**Issue by jiljoel** [The-Nexus-Project/Limitless-5#191]
### What happened?

Hi,

Actually, When I get the "buff" levitation from food (comfort) when the timer reaches 00:00 it does not stop.

I tried milk and one of the edible berrys that cancels a potion effect but it did not worked.
I've to quit game an launch again to fix it .

thanks.

### Pack Version

Version: 2.21.1

### To Reproduce

1. eat something with the buff comfort wich gives comfort and levitation
2. wait until the timer reaches 00:00

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

**Comment by Gbergz** [comment]
Caused by the Potion ID hitting its limit, and there's nothing I can do about it right now. Sorry.
Use /kill to make it go away.
