### ISSUE TITLE
[Issue]: Eccentric Tome shows "Engineer's Decor" twice

### ISSUE THREAD

**Issue by toqueteos** [The-Nexus-Project/Limitless-5#192]
### What happened?

Eccentric Tome shows "Engineer's Decor" twice

### Pack Version

Version: v2.21.1

### To Reproduce

1. Open `Eccentric Tome`
2. Look for `Engineer's Decor`
3. It appears twice

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

### Anything else to add?

![image](https://user-images.githubusercontent.com/699969/190924220-ad47511b-09e0-4488-9bee-581a1f28ba4e.png)

**Comment by Gbergz** [comment]
This isn't really an issue, I just accidentally put it in twice.
Enjoy two Engineer's Decor manuals. x)

**Comment by PhantomEnderium** [comment]
If it's really such a bother, it can probably be modified with commands xd
