### ISSUE TITLE
[Issue]: Withered Comb quest triggers error

### ISSUE THREAD

**Issue by toqueteos** [The-Nexus-Project/Limitless-5#193]
### What happened?

A quest from Productive Bees triggers an error when you click on it for the recipe.

### Pack Version

Version: v2.21.1

### To Reproduce

1. Open Quest Book
2. Go to Productive Bees chapter
3. Click on the Withered Comb quest
4. Click on the Withered comb on the left side
5. Error will pop out on the top right corner

Here's steps on video:
https://user-images.githubusercontent.com/699969/190924572-5e6b9912-1fe7-45b0-ba93-9368e4b21bda.mp4

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

**Comment by Gbergz** [comment]
Not an issue, read the readme note.

**Comment by toqueteos** [comment]
My bad, sorry.

**Comment by Gbergz** [comment]
No worries!
