### ISSUE TITLE
[Issue]: Meals from Lunch Box (cyclic) do not fullfill nutrition values

### ISSUE THREAD

**Issue by Slither88** [The-Nexus-Project/Limitless-5#196]
### What happened?

I crafted a Lunch Box from Cyclic and placed some food in there. The first one being Banana Bread but when I ate it the relevant nutrition bars did not go up.

### Pack Version

Version: v2.22.0

### To Reproduce

1.Place food in lunch box
2. Eat

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

**Comment by Gbergz** [comment]
I do not think this is something as pack developer I can fix.
Report to the dev and see what they can do about it.

Thanks for report though.
