### ISSUE TITLE
[Issue]: Items not stacking/merging

### ISSUE THREAD

**Issue by Repa1253** [The-Nexus-Project/Limitless-5#197]
### What happened?

Items that are the exact same sometimes refuse to merge and stack in inventories.
Can be temporarily fixed by throwing both stacks on the ground and letting them merge on the floor

### Pack Version

Version: 1.18.2

### To Reproduce

1. Destroy and/or pick up items and place them in inventory
2. Picked up items sometimes don't merge with exact items already in inventory

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

### Anything else to add?

Let me know if a log is needed. I don't know if I can catch that in a log.

**Comment by Gbergz** [comment]
Already being investigating in discord, will update here once it's solved.

Probably won't be fixed for awhile since I need to actually find the mod in this sea of mods.

**Comment by Repa1253** [comment]
Aight, thanks.

**Comment by Gbergz** [comment]
Fixed in v2.23.1
