### ISSUE TITLE
[Issue]: effects not ending

### ISSUE THREAD

**Issue by DiehardRuby** [The-Nexus-Project/Limitless-5#198]
### What happened?

hello i have been playing the mod pack lately and have noticed that some effects don't go away after the timer has run out. for instance levitation, dolphins embrace and so on. the only way to fix it was to log out and back in. which is annoying so thought i would just let you know.

### Pack Version

Version: 2.23.0

### To Reproduce

1. find a scroll with magic properties 
2. use said scroll
3. wait timer 
4. and done 
there isn't much else to it

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

### Relevant log output / crash report.

```shell
none
```

**Comment by Gbergz** [comment]
duplicate https://github.com/The-Nexus-Project/Limitless-5/issues/191
