### ISSUE TITLE
Mods I loved when I used.

### ISSUE THREAD

**Issue by BuddyBoi9** [The-Nexus-Project/Limitless-5#200]
### What's your suggestion / feature request?

Create:Crystal Clear, Create : Misc & Things, Italian's Delight, Cultural Delights, BetterF3

**Comment by Gbergz** [comment]
https://github.com/The-Nexus-Project/Limitless-5/issues/1

**Comment by BuddyBoi9** [comment]
huh?

**Comment by Gbergz** [comment]
#1 for mod suggestions
