### ISSUE TITLE
[Issue]: Unable to craft Deepslate Seed from Mystical Agriculture

### ISSUE THREAD

**Issue by CalvinSoHK** [The-Nexus-Project/Limitless-5#202]
### What happened?

Tried to follow the recipe shown for Deepslate Seed from Mystical Agriculture, but doing so only results in Stone Seed.
When looking at the Stone Seed recipe it seems to take many types of Stone (Cobblestone, Stone, Andesite, etc), there is probably just a recipe conflict.

### Pack Version

Version: 24.0

### To Reproduce

1.Try to craft Deepslate Seed using Infusion Altar and Infusion Pedestal
2.Returns a Stone Seed instead of expected Deepslate Seed

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

**Comment by Gbergz** [comment]
Already reported and this is not on us, but can probably be fixed.
