### ISSUE TITLE
[Issue]: Crash when picking up Shulker with Backpack

### ISSUE THREAD

**Issue by Subi-alt** [The-Nexus-Project/Limitless-5#203]
### What happened?

Singleplayer Game Crashes when Sophisticated Backpack picks up a Shift Broken Lootr Shulker

### Pack Version

Version: 2.24.0

### To Reproduce

1. Have a Sophisticated Backpack on with a pickup upgrade. (For reference, I had a netherite backpack with no other upgrades other than pickup).
2. Go to the end where there are Lootr shulker boxes.
3. Shift break one with a shulker dropping.
4. Have it picked up with the backpack.
5. See that you have crashed.

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [x] Using Rubidium
- [ ] Using Rubidium + Oculus
- [ ] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [x] No.

### Relevant log output / crash report.

```shell
https://pastebin.com/Nr7DNG2V
```

### Anything else to add?

It did not crash when I picked it up without the backpack.

**Comment by Gbergz** [comment]
Report it to the Sophisticateds Issue tracker.
