### ISSUE TITLE
[Issue]: IndexOutBoundsExeption

### ISSUE THREAD

**Issue by CrazyDev05** [The-Nexus-Project/Limitless-5#204]
### What happened?

When i tried to join my freshly installed selfhosted server, i got a IndexOutBoundsExeption
![image](https://user-images.githubusercontent.com/47589149/196761063-d1cdacb4-3ef9-470a-bc45-6f57d96a8058.png)

### Pack Version

Version: 2.24.0

### To Reproduce

1. install the pack on both server and client
2. start both
3. try to join the server

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

**Comment by Gbergz** [comment]
logs please

**Comment by CrazyDev05** [comment]
Client:
[19:14:10] [Render thread/INFO]: Connecting to crazy-dev.de, 25565
[19:14:10] [Netty Client IO #0/WARN]: Packet not registered: ClientboundLoginDisconnectPacket
Server shows no reaction

**Comment by CrazyDev05** [comment]
[latest.log](https://github.com/The-Nexus-Project/Limitless-5/files/9822891/latest.log)

**Comment by CrazyDev05** [comment]
do you also need the server logs?

**Comment by Gbergz** [comment]
re-install everything from scratch- transfer world if you have one. Switch to ATLauncher.
and server logs would probably be nice too

**Comment by CrazyDev05** [comment]
the server logs:
[latest.log](https://github.com/The-Nexus-Project/Limitless-5/files/9822905/latest.log)

**Comment by Gbergz** [comment]
Server seems fine, but re-install everything from scratch- transfer world if you have one. Switch to ATLauncher.

**Comment by CrazyDev05** [comment]
should i also reinstall the server?

**Comment by Gbergz** [comment]
wouldn't hurt

**Comment by CrazyDev05** [comment]
[server.log](https://github.com/The-Nexus-Project/Limitless-5/files/9823086/server.log)
[client.log](https://github.com/The-Nexus-Project/Limitless-5/files/9823089/client.log)

**Comment by Gbergz** [comment]
I can't reproduce the issue, tried myself to install fresh server, from CurseForge, GDLauncher & ATLauncher. All work just fine.
Not clue why it isn't working for ya, I am sorry... hm..

**Comment by CrazyDev05** [comment]
what java version are you using on the server?

**Comment by CrazyDev05** [comment]
lol i restarted client and server and now it works

**Comment by Gbergz** [comment]
Modded mc sometimes 🤔

**Comment by CrazyDev05** [comment]
i'll close this issue then
