### ISSUE TITLE
[Issue]: All known Chunkloaders?

### ISSUE THREAD

**Issue by cauliflower69** [The-Nexus-Project/Limitless-5#205]
### What happened?

Apart from FTB Chunks which chunk loaders are there so I can disable them please.

What happened?
A player has dropped an insane amount of items on the server and I would like to disable all loaded chunks

### Pack Version

Version: 2.25.0

### To Reproduce

1. Drop an insane amount of items

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

### Anything else to add?

Using the kill all dropped items command will not work as the server is lagging so much

**Comment by Gbergz** [comment]
With some googling, you can find that you can disable the forceloading in ftb chunks in the serverconfig / configs.

This is not really a pack issue, per say.
Closing.

If you don't mind, lets continue this in the discord instead, better. **#support**.
https://discord.gg/gwzpyQb
