### ISSUE TITLE
[Issue]: typing "r" into JEI searchbar crashes my game

### ISSUE THREAD

**Issue by brownbricks99** [The-Nexus-Project/Limitless-5#207]
### What happened?

Trying to type "vertical" in the JEI searchbar, it crashes when i type the letter "r" into it.

### Pack Version

Version: 2.23.1

### To Reproduce

1. press E
2. type "vertical" into the JEI searchbar

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [X] Using Rubidium
- [ ] Using Rubidium + Oculus
- [ ] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

### Relevant log output / crash report.

```shell
https://bytebin.lucko.me/HMTVGFGa1g
```

**Comment by Gbergz** [comment]
Had my instance open so I could test this very quickly.
Can't reproduce it, game doesn't crash.

But it seems to be caused by something from Computer Craft.

Can you reproduce it without Rubidium?

**Comment by Gbergz** [comment]
Also update to 2.25.0 and see if you can reproduce it there.

**Comment by brownbricks99** [comment]
i updated and it works again
