### ISSUE TITLE
[Issue]: The dropped items not showing. The mobs not showing.

### ISSUE THREAD

**Issue by Sasikaa** [The-Nexus-Project/Limitless-5#208]
### What happened?

The installed game, first run. The dropped items is not showing, the mobs not showing. The start bonus chest is not showing, only the four torch araound it.

### Pack Version

Version: TNP limitless 5 1.18.2 2.25.0

### To Reproduce

1.

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [X] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

### Relevant log output / crash report.

```shell
Nothing crash. Just not see any mobs and dropped items...
```

**Comment by Sasikaa** [comment]
Now trying:
- Enabled shitty creeper mods, beacuse this is one mod is disabled. (SOLVED?)
- Trying deleting, and downloading the modpack again. (The first install is corrupt? because I downloading curseforge client, and the installing 1-2 minutes. And not see play button, only install button. Secound try downloading and installing all mods.) (SOLVED?)

**Comment by Gbergz** [comment]
It's as simple as restarting the game once or twice. It's an uncommon bug.

**Comment by Gbergz** [comment]
Also try without Rubidium and Oculus. Could be the issue if you're having it all the time

**Comment by Sasikaa** [comment]
First try not install rudi and ocul mods. Secound try install and sahder pack. Now, reinstall 5 and 6 TNP version, and fabric version. Trying. But the loading time is shit, approx 5-10 minutes loading time is not try-friendly...

**Comment by Gbergz** [comment]
I have no clue what you're talking about anymore. 😅

**Comment by Gbergz** [comment]
Anyway. The solution is my last comment. Continue in discord for further help if needed.
