### ISSUE TITLE
[Issue]: Game crashes right after spawning in it

### ISSUE THREAD

**Issue by Nebelraucher** [The-Nexus-Project/Limitless-5#209]
### What happened?

After the first completly random crash i wanted to join again but right after joining it crashes again.

### Pack Version

Version: 2.26.0

### To Reproduce

1.Joining world

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

### Relevant log output / crash report.

```shell
https://bytebin.lucko.me/Jw0UN2gvV8
```

**Comment by Gbergz** [comment]
Known issue. Will get a hotfix out once it can be solved.

**Comment by Gbergz** [comment]
So soon-ish.

**Comment by Gbergz** [comment]
Stay away from Ferrets, from the mod Critters and Companions for now.

**Comment by RealTrueDeviL** [comment]
I just updated to the latest version, played for like 1 hour, then same happaned to me, I was just in my base, building, and doing nothing special, now I cannot load into the world, I understand "it's known" but here's my crash log, in case you need it also - https://bytebin.lucko.me/uhC2M3vS8t

**Comment by Gbergz** [comment]
Nothing I can do about it any further, it's an issue in GeckoLib, which has been fixed in there, now mods need to update to support it!

**Comment by RealTrueDeviL** [comment]
Ahh ok fair enough, I'll wait for an update then.. Thanks

**Comment by TiberOctum** [comment]
Didn't realize my report was basically the same as here, sorry.

Thanks for all your good work.

**Comment by Gbergz** [comment]
Should be fixed in newer updates.
