### ISSUE TITLE
[Issue]: Forced logout while opening questbook

### ISSUE THREAD

**Issue by AirflashX** [The-Nexus-Project/Limitless-5#210]
### What happened?

Local crashed after opening the questbook.
Got this errorlog: https://bytebin.lucko.me/H27xmjKbeT

### Pack Version

Version: Limitless-5-2.26.1

### To Reproduce

1. Updated to 2.26.1
2. Ingame, pressed E and then clicked top left on "Quests"
3. Crash

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [ ] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [ ] No.

**Comment by Gbergz** [comment]
I am in-game right now to test this, can't reproduce.
Also please fill in the issue report...
