### ISSUE TITLE
[Issue]: It Say That The Application Doesn't Respond Anymore When The Startup Bar Is At The End

### ISSUE THREAD

**Issue by super3559** [The-Nexus-Project/Limitless-5#213]
### What happened?

The Title Say What Happened. I Have Installed Java 17 And Have Allocated Over 7 GB Of Memory.

### Pack Version

Version: 2.26.2

### To Reproduce

1.Idk Probably My Setup That Crash It But I Whant To Be Sure

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [x] No.

### Relevant log output / crash report.

```shell
Can't Be Any It Just Say That The Application Doesn't Respond Anymore.
```

**Comment by super3559** [comment]
The Only Thing I can Think Of Doing Is Installing The Client : (

**Comment by Gbergz** [comment]
Let's take this to the discord instead. Which you've already done so no need to open an issue about it here.

**Comment by super3559** [comment]
ok sorry
