### ISSUE TITLE
[Issue]: Fae Court sanctum clashed with lanterns

### ISSUE THREAD

**Issue by mattsam1234** [The-Nexus-Project/Limitless-5#216]
### What happened?

The fae court sanctum ritual for Mana and Artifice, I cannot complete the structure as the lanterns it is looking for are specifically Minecraft ones. When placed in game the lanterns become Additional Lanterns block and do not work for the structure.

### Pack Version

Version: 2.26.2

### To Reproduce

1. get to level 3 mana and artifice and ally with fae court 
2. Perform ritual of sanctum court 
3. Click the block to generate preview and build until lanterns appear.
4. Place lanterns in the slot and see they do not get accepted

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

**Comment by Gbergz** [comment]
Thanks for reporting, I will have this fixed for the next update!
