### ISSUE TITLE
[Issue]: LazierAE2 Recipies bugged after update

### ISSUE THREAD

**Issue by AptGetGnome** [The-Nexus-Project/Limitless-5#217]
### What happened?

After updating to the latest version of the pack from the last version, I noticed no issues however when i started working with LazierAE2 I noticed all the recipies that used the machines in the pack were not showing, I can for instance make the Fluix Aggregator or the Matter Infuser, but some of the parts (mostly the ingots or other ingredients that require inscribers) are not visable as what its recipie is, and since i recalled some of them i tried to craft them anyway thinking it was a JEI bug however it won't craft either.

I created a completly new instance of TNP5 in my launcher (ATLauncher) and the issue doesn't occur.

My problem is if i was fresh i wouldn't mind, but I am running a server for a friend and I that we just setup last version, when i moved the world folder to the new server instance, we have had no issues, BUT now this issue is occuring, what can i change in my files so that i can fix the problem without having to lose all progress?

### Pack Version

Version: TNP Limitless 5 - 1.18.2

### To Reproduce

1.Update from previous version
2.LazierAE2 has issues

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [X] No.

**Comment by Gbergz** [comment]
Because LazierAE still doesn't support JEI 10. 

Devs need to update support.

Not on us

**Comment by Gbergz** [comment]
You also wrote in 3 different places.
Only one is needed. The original comment in discord. :)
