### ISSUE TITLE
Clicking items into items

### ISSUE THREAD

**Issue by Ralloonx** [The-Nexus-Project/Limitless-5#22]
I've never seen this before. What mod does it? Because I want to remove it.

Glass panes can literally be clicked inside of stone walls. And signs can be clicked into other signs, so it shows up in one block. Like a whole stack of signs can be clicked into one spot. I've tried clicking an entire stack into one spot to see if a stack would let me place a sign before another sign, only to have everything returned once you hit the stack limit. I can't place signs at all like you can in vanilla. 

The problem here is that I can't build the iron farm I want because I can't click signs properly anymore to hold fluids in place. It's really frustrating.

**Comment by Gbergz** [comment]
https://www.curseforge.com/minecraft/mc-mods/plonk

**Comment by Ralloonx** [comment]
Thank you, but that doesn't work. I'll simply remove the mod.

**Comment by Gbergz** [comment]
I don't understand your initial message though. Plonk only happens if you click the keybind. Never otherwise.

**Comment by Ralloonx** [comment]
Plonk isn't the issue. This is frustrating. (I removed Plonk and the issue remains.)

I put down a wall block, then tried to place a glass pane on top of it. Instead the two blocks end up in the same place, becoming one block. You can see bits of glass showing on the wall. Use a pick axe and you get both pieces back. (Which is weird, because I'm not using silk touch.)

With signs, I place one sign, and that goes up normally. Shift click another sign, and instead of being in the block in front of the first sign, it places inside of the first sign. You can do this for fifteen signs, it looking like only one sign, but if you place sixteen, fifteen signs will fall down, leaving the first still in place.

I've never encountered this before this modpack.

**Comment by Gbergz** [comment]
Could be this?
https://www.curseforge.com/minecraft/mc-mods/windowlogging

**Comment by Ralloonx** [comment]
Thank you so much for your prompt replies, and help.

Sadly Windowlogging is not it either.

**Comment by Gbergz** [comment]
Np.
Can you make a video of the problem? Kind of hard to understand in text it seems.

**Comment by Ralloonx** [comment]
I really have no way of doing that, I'm sorry.

I don't have a way to record, or compile, or anything.

It's literally placing multiple items into the same block. It looks like only one item, but that one block holds up to 16 signs. Kind of like entity cramming. You can have multiple cows in one spot and sometimes they can look like only one cow? That's how it is with signs.

I've even tried writing on the signs to see if the text will make a difference, but no. Different wood type signs don't matter. They all just shift click in together.

**Comment by Gbergz** [comment]
Is this the issue you're having?
https://streamable.com/hzhoxw

**Comment by Ralloonx** [comment]
Yes, that is.

**Comment by Gbergz** [comment]
Then it's the Windowlogging mod. It's what causing that.

And the sign issue you're having, it's not placing a sign. You're trying to edit the contents on a sign (added by Quark), visual glitch that you're placing it.
Vid here: https://streamable.com/pdx8cr

**Comment by Ralloonx** [comment]
Is there anyway to remedy this other than removing quark?

**Comment by Gbergz** [comment]
Turns out VanillaTweaks also adds a Sign Editing tweak. Disable that. And then go into quark config and disable it there too.
That should allow you to place signs onto other signs etc.

**Comment by Ralloonx** [comment]
I've reinstalled the pack, changed all the configs,  and am still having this issue. Right now I'm going to stop playing with it and move on. 

Thank you so much for all your time and help.

**Comment by Gbergz** [comment]
If you read and do what I told you. It will be fixed.
