### ISSUE TITLE
Sophisticated Backpacks failed to load

### ISSUE THREAD

**Issue by RustyJager** [The-Nexus-Project/Limitless-5#225]
### What happened?

Can't even launch it without this error, I've installed 3 different versions of Sophisticated backpacks separately and even tried to play it without that mod and get even more errors..

### Pack Version

Version: 2.29.0

### To Reproduce

1. launch game

### Are you using OptiFine, Rubidium, or Oculus?

- [X] Using OptiFine
- [ ] Using Rubidium
- [ ] Using Rubidium + Oculus
- [ ] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

### Relevant log output / crash report.

```shell
[crash-2023-01-09_17.26.19-fml.txt](https://github.com/The-Nexus-Project/Limitless-5/files/10377446/crash-2023-01-09_17.26.19-fml.txt)

[crash-2023-01-09_17.26.19-fml.txt](https://github.com/The-Nexus-Project/Limitless-5/files/10377416/crash-2023-01-09_17.26.19-fml.txt)
```

**Comment by Gbergz** [comment]
Answered in discord.
