### ISSUE TITLE
[Issue]: JEI Searching Causes Crash

### ISSUE THREAD

**Issue by RConTRS** [The-Nexus-Project/Limitless-5#228]
### What happened?

Searching In JEI Causes Crash Sometimes Uncommonly, Providing No Crash Report So I Only Got The Log and debug
BTW I Have Been Using Rubidium In Pack Version 2.30.0 Without Any Problems

[latest.log](https://github.com/The-Nexus-Project/Limitless-5/files/10762434/latest.log)
[debug.zip](https://github.com/The-Nexus-Project/Limitless-5/files/10762436/debug.zip)

### Pack Version

Version: 2.31.0

### To Reproduce

1. Search In JEI
2. The Game Has A Chance To Freeze And Then Eventually Crash

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [X] Using Rubidium
- [ ] Using Rubidium + Oculus
- [ ] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

**Comment by apelozi** [comment]
Try removing mod Jeed, worked for me

**Comment by RConTRS** [comment]
TY it worked, i will consider the issue solved
