### ISSUE TITLE
Certain chunk softlocks game

### ISSUE THREAD

**Issue by Fuzsoo** [The-Nexus-Project/Limitless-5#23]
Pack version: 0.15.0 & 0.16.0
Java: 17.0.2.0

I have a very specific bug that breaks my singleplayer game. When i enter a specific area the world starts to disappear behind me and it softlocks the game. I can still move and some parts of the world still loads in but entities and commands stop working and it wont let me interact with anything anymore. when trying to close the world it wont get past the saving world and have to force close minecraft. It also doesn't give me a crash report so i cant really figure it out myself why this happens.

I tried this on a second pc with a clean install on it and got the same outcome. To recreate this bug i did the following:
1. Create a new default game with the seed "6116606995777965047" and give yourself creative and cheats
2. Load into the game and use /tp "PlayerName" 4500 90 -1200
3. Fly a little bit to the east around X 4700
4. See the world behind you dissapear

**Comment by Gbergz** [comment]
Can reproduce this myself, but I've also created atleast 50+ worlds now and only this worlds seed has this issue.

**Comment by Fuzsoo** [comment]
I wish i had this luck with the lottery. Any idea which mod this causes or you think its better for me to change world?

**Comment by Gbergz** [comment]
Is this still an issue in the newest pack updates?

**Comment by Fuzsoo** [comment]
Yes, a newly generated world and the old save with that seed still has the problem.

**Comment by Gbergz** [comment]
That's so weird, only that seed it seems. 
Never encountered this myself on new worlds, only on that seed.

**Comment by Gbergz** [comment]
Closing, seems like a VERY rare occurrence.
