### ISSUE TITLE
[Issue]: Still have conflict recipes for fruit in furnace

### ISSUE THREAD

**Issue by MarkIc5785** [The-Nexus-Project/Limitless-5#233]
### What happened?

#175 
Same as it. All fruits are baked into dryed nuts. That might be a minor problem, until we find it impossible to get popped chorus.
Pam's is on 1.0.1, btw.

### Pack Version

Version: 2.34.1

### To Reproduce

1.Cook any fruits in furnace.

### Are you using OptiFine, Rubidium, or Oculus?

- [ ] Using OptiFine
- [X] Using Rubidium
- [ ] Using Rubidium + Oculus
- [ ] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

**Comment by Gbergz** [comment]
Limitless 5 is not updated so often, so if this is an issue (still), it will not be fixed very fast.

**Comment by Gbergz** [comment]
Use Polymorph and choose output, it is in the pack.

**Comment by MarkIc5785** [comment]
Well, that can be a solution. I ignored it because polymorph doesn't work on modded furnaces. Quite confusing though, maybe a note in quest can help.
