### ISSUE TITLE
Can't enter the nether

### ISSUE THREAD

**Issue by lustigsw** [The-Nexus-Project/Limitless-5#24]
We just created a nether portal and was auto-kicked when attempting for our first time. We keep getting auto kicked and after 3 attempts of signing back in we get spawned back in to the overworld.

**Comment by Gbergz** [comment]
This is a Terrablender issue, hopefully will be fixed .

**Comment by Gbergz** [comment]
Try removing the mod Amplified Nether.

**Comment by lustigsw** [comment]
The error I get is:
Caused byjava.lang.NullPointerException: Cannot invoke "terrablender.worldgen.TBClimate$RTree.search(terrablender.worldgen.TBClimate$TargetPoint, terrablender.worldgen.TBClimate$DistanceMetric)" because "this.trees[uniqueness]" is null

**Comment by Gbergz** [comment]
Yes. It's reported in Terrablender already. And no idea when it'll get fixed.

**Comment by Gbergz** [comment]
Will be fixed when pack eventually jumps to 1.18.2
