### ISSUE TITLE
throws out game crash

### ISSUE THREAD

**Issue by void513** [The-Nexus-Project/Limitless-5#25]
this only seem happen when someone joins the game and get shot by a arrow from skeleton of Hunter Illager. Heres the crash report.
https://www.pastiebin.com/62058ece5dcd6

**Comment by TrollHax** [comment]
I can confirm that this also happens to me. For me, it happened when a skeleton shot an arrow that got deflected by my spell stone from the mod "Enigmatic Legacy"

**Comment by Gbergz** [comment]
Is this solved?
