### ISSUE TITLE
crashes when you try attach a xnet connector to a alloy smelter from Industrial Reborn

### ISSUE THREAD

**Issue by void513** [The-Nexus-Project/Limitless-5#26]
It crashes when i try  to attach a red connector from xnet to a allloy smeltry from Industrial Reborn. And save game crashes every time you load up after.Heres the crash report. 
https://www.pastiebin.com/6207fd015e7b3 
i may send a crash report to both mods in hope this help get it fix

**Comment by Gbergz** [comment]
Hey, can you report this to either Industrial Reborn or Xnet?

**Comment by void513** [comment]
already on it bro.

**Comment by void513** [comment]
i reported it to both and updated xnet to latest version and tryed again with same results..

**Comment by void513** [comment]
just heard back from xnet they closed it  saying it is  a  industrial reborn problem .so im wait to hear from them

**Comment by Gbergz** [comment]
Closing this now as the mod is removed in the 2.0 update.
