### ISSUE TITLE
Crafting wood jetpack does not complete quest

### ISSUE THREAD

**Issue by Xplodin** [The-Nexus-Project/Limitless-5#27]
On official na server
![2022-02-18_10 03 17](https://user-images.githubusercontent.com/13007677/154707807-dde5f969-aac5-4bc8-9dd3-ecdd04b28bd8.png)

![2022-02-18_10 03 49](https://user-images.githubusercontent.com/13007677/154707924-e215740d-abd8-4be5-8a7f-a58050333fba.png)

**Comment by Gbergz** [comment]
Already known. Been discussing this in the TNP Discord. Continues there.
