### ISSUE TITLE
Corail Tombstone enchanted books limited to V

### ISSUE THREAD

**Issue by DORINI00** [The-Nexus-Project/Limitless-5#28]
Hello, I have noticed that the enchanted books of the mod Corail Tombstone are limited to level V or have doubles in JEI:
-Shadow Step V
-Magic Siphon V
-Plague Bringer V
-Curse of Bones V
-Frostbite V

**Comment by Gbergz** [comment]
Most likely an issue with Apotheosis. Since it handles all enchants over their usual limits.

**Comment by Gbergz** [comment]
And the duplicates of the V enchantments are probably the books that would be, VI, VIII etc etc.

**Comment by Corail31** [comment]
@Gbergz If you want the limit to be 9 in recent versions, make sure to configure max enchantment levels in the Corail Tombstone's config (because enchant limits are enforced against mixin).

**Comment by Gbergz** [comment]
@Corail31 Gotcha, thanks. Didn't know this. Will change the configs :)
