### ISSUE TITLE
Botania?

### ISSUE THREAD

**Issue by SavannahGrace3** [The-Nexus-Project/Limitless-5#29]
Have you thought about or try adding the Botania Modpack? Limitless 5 has every thing my friends and I want in a modpack except Botania. However, I think I have read that they havent updated that modpack in awhile... I'm not sure if thats still the case or not but we've love to have it :) Well I meant to put this in suggestions but Im still new at github and cant find a delete button.. my apologies

**Comment by Vexalus** [comment]
Botania's a mod, not a modpack. But anyhow, it literally just got updated to 1.18 today, it'll be in the next update.

**Comment by Gbergz** [comment]
Keep mod suggestions here: https://github.com/The-Nexus-Project/Limitless-5/issues/1
