### ISSUE TITLE
I am unable to join the TNP Limitless 5 server as I keep getting disconnected each time

### ISSUE THREAD

**Issue by aurimilky** [The-Nexus-Project/Limitless-5#3]
So I was playing on your server TNP Limitless 5 and I had just killed a pillager that had gotten it self trapped in village. after it was killed I when into one of the villager's buildings just to turn around to see two more of the pillagers coming in the door. I did try killing them but I got killed. then my game got dc from the server. I tried to rejoin the server but each time I did I would get dc each time. after hours of trying to rejoin the server I finally got on. I used /rtp to get out of spawn and I used the key to get back to my grave so that I could get my stuff back. then my minecraft dc again. I am unable to join to server as I keep on getting dc.

I triedfollowing flush ip, ccleaner and deleting temp folder but still can got the server.

I some photos of the error messages that minecraft gave me.

https://i.imgur.com/gB7OlDh.png

https://i.imgur.com/F9fWZDg.png

https://i.imgur.com/kVVa1tm.png

https://i.imgur.com/GbHDwDO.png

https://pastebin.com/RY65FSgp

https://pastebin.com/

many thanks
ashton

**Comment by Gbergz** [comment]
Hey join our discord and discuss this instead of here
https://discord.gg/gwzpyQb

**Comment by aurimilky** [comment]
ok will do
