### ISSUE TITLE
Game crash while placing item from lootbag

### ISSUE THREAD

**Issue by OliwkaBrazill** [The-Nexus-Project/Limitless-5#32]
Hey, I was playing on the EU server Limitless I got crashed when I put the object on the ground, it was floating Mari something I forgot the name of the flower, anyway, I got it from the loot bag. I can't join the server, it still crashing me and in logs, there are that I join and left in one second, 
![obraz_2022-03-01_213111](https://user-images.githubusercontent.com/100726467/156244246-01a35165-b4a0-4e29-a097-623e55a900ba.png)

**Comment by Gbergz** [comment]
Send that report

**Comment by OliwkaBrazill** [comment]
https://bytebin.lucko.me/fYgfqhoiKx

**Comment by Gbergz** [comment]
Seems to be this item: `Name: botania:marimorphosis // vazkii.botania.common.block.subtile.functional.SubTileMarimorphosis`

**Comment by OliwkaBrazill** [comment]
that was it, idk you can somehow force take it from me? I cant join the server

**Comment by Gbergz** [comment]
I'll close this issue here and we can continue talking about this issue on the discord server in #support.
