### ISSUE TITLE
FTBChunks chunk loading doesn't seem to work

### ISSUE THREAD

**Issue by WiktorGast** [The-Nexus-Project/Limitless-5#36]
I have force loaded chunks in the following dimensions:

• The Overworld
• The Nether
• The Mining dimension

But they don't actually seem to be loaded at all seeing that I don't get any lava from my nether pump when I'm not there, nor is my quarry in the mining dim getting any power when I'm not in my base in the overworld.

**Comment by Gbergz** [comment]
This is already known from our Discord, most likely an FTB Chunks issue, look for an issue regarding it on their issue tracker. 

Open a new report if you can't find anything.

**Comment by WiktorGast** [comment]
Thanks for the tip, there's indeed an issue for this on their issue tracker so I'll be watching that for any fix.
