### ISSUE TITLE
Crash with 4-book pile from Supplementaries (v1.0.0)

### ISSUE THREAD

**Issue by HappyeDiscord** [The-Nexus-Project/Limitless-5#38]
If you stand too close or jump on a pile of 4 enchanted books that you've placed in the world because of Supplementaries, you get booted to crash screen. Easily replicable, doesn't seem to care about enchantments on the books themselves. Apologies if this has already been fixed in later versions.

**Comment by void513** [comment]
confirm that it crashes and have sent a crash report to there issue tracker

**Comment by Gbergz** [comment]
https://www.curseforge.com/minecraft/mc-mods/supplementaries/issues/281
