### ISSUE TITLE
Server crash while exploring the nether

### ISSUE THREAD

**Issue by MAChadwick** [The-Nexus-Project/Limitless-5#39]
Hi! Sometimes when exploring the nether, the entire server crashes. It's happened about 5 times at this point. I tried deleting the nether world folder to no avail. I've attached the server crash log.

[Pastebin](https://pastebin.com/8Lq2JFUp) in case you don't want to download the file.

[crash-2022-03-15_22.00.53-server.txt](https://github.com/The-Nexus-Project/Limitless-5/files/8258361/crash-2022-03-15_22.00.53-server.txt)

**Comment by Gbergz** [comment]
https://github.com/The-Nexus-Project/Limitless-5/issues/24

**Comment by Gbergz** [comment]
Should be fixed in 1.18.2 update. (v2.0+)
