### ISSUE TITLE
[Issue] ranged pumps 0.9.0 broken

### ISSUE THREAD

**Issue by StephenLujan** [The-Nexus-Project/Limitless-5#42]
### Problem
At the time of creating this issue the ranged pumps mod latest release is 0.9.0, but it is really rather broken in minecraft 1.18, as it tries to scan down to y = 0 and if below y = 0 it scans down to -infinity without expanding horizontally. So it's a bit useless for sucking up lava. It is already patched in their code, but not released. Just creating a placeholder issue here to keep track and for anyone else dealing with it to understand the problem.

see: https://github.com/refinedmods/rangedpumps/issues/37

### Affected Version
1.2.0

**Comment by Gbergz** [comment]
should be fixed in newer versions
