### ISSUE TITLE
TNP 1.4.0 Crash

### ISSUE THREAD

**Issue by MrSheen123** [The-Nexus-Project/Limitless-5#43]
### Are you using OptiFine?
No

### Describe your issue, what happened?

Server crash on start up. Windows states the below and Linux (my main place I host it) shows the error in the pastebin below
Error: Could not find or load main class @libraries.net.minecraftforge.forge.1.18.1-39.0.88.win_args.txt

I tried re-installing forge a couple times to make sure it wasn't a fluke or bad config

### To Reproduce

Download server
Launch server
Server crashes

### Expected behavior
Server launches and is playable

### Crash Reports & Logs (Don't paste entire crash reports here.)
https://pastebin.com/7f0WJ1Ah

### Affected Version
- Pack Version: V1.4.0
- On a server?: Yes

**Comment by Gbergz** [comment]
Install java 17

**Comment by MrSheen123** [comment]
Ah okay yeah I see that for my Windows install but my linux server is running with a java 17 docker image

**Comment by MrSheen123** [comment]
Tried re-adding java 17 docker image to my linux server and it still comes with the same crash in the pastebin unfortunately :(

**Comment by Gbergz** [comment]
Well that crash is Java 17 not being recognized

**Comment by MrSheen123** [comment]
Hmmm okay, I will try a fresh setup and see if that works. Thank you
