### ISSUE TITLE
[Issue] anything that is not a block is invisible 

### ISSUE THREAD

**Issue by warpath1985** [The-Nexus-Project/Limitless-5#44]
### Are you using OptiFine?
no optifine

### Describe your issue, what happened?
looking for a pack to play and stream with a group of friends 
in creative exploring what the pack has to offer content wise  i noticed id not seen a single mob/animal/ villager yet i can hear them 
found  chest emptied it on the ground all items invisible but are there to collect

### To Reproduce

launch single player world and explore

### Expected behavior
as stated above no entity is visable

### Screenshots

![2022-04-03_14 32 48](https://user-images.githubusercontent.com/6086520/161430578-1625f147-2a60-43ec-9197-a393ac15a241.png)
with in this photo that hole has about 8 cows placed from spawn egg i hear them i see the health bar top screen  but they are invisable 
### Crash Reports & Logs (Don't paste entire crash reports here.)
no crash

### Affected Version
1.4.0
- Pack Version: 
- On a server?:

**Comment by Gbergz** [comment]
Tried this myself, and I can't seem to reproduce it.
There is mods that make "not visible" entities invisible to improve performance. Perhaps this is a case where it thinks they're behind something and hides them.

**Comment by warpath1985** [comment]
i can throw items out in front of me  and i cant see them  but i can pick them bk up walking over them

**Comment by Gbergz** [comment]
I would reinstall. 
Try MultiMC if you are using CurseForge

**Comment by warpath1985** [comment]
okay i think ive cracked it  doing a relaunch  i cna see enities now
