### ISSUE TITLE
[Issue] Floating Hopperhock client crash

### ISSUE THREAD

**Issue by lordtrickster** [The-Nexus-Project/Limitless-5#45]
### Describe your issue, what happened?
Placing a floating hopperhock (Botania) causes a *client* crash, server stays up fine.  Tested with Botania by itself in a custom pack, had no issue.

### To Reproduce
1. Place a floating hopperhock
2. See error

### Expected behavior
No crash

### Affected Version
- Pack Version: 1.4.0
- On a server?: Tested both on a server and in single player

**Comment by Gbergz** [comment]
Yep, known issue. Not sure if it has been reported to the Botania devs yet.
