### ISSUE TITLE
[Issue] Boon of the Earth drops unusable ores

### ISSUE THREAD

**Issue by CephalonRho** [The-Nexus-Project/Limitless-5#47]
### Describe your issue, what happened?
Mining stone using a pickaxe with the "Boon of the Earth" Enchantment from Apotheosis can drop unusable ores (like Mekanisms Lead Ore and Uranium Ore, both blacklisted in JEI). This seems to be because they have the `apotheosis:boon_drops` tag.

### To Reproduce
1. Enchant a pickaxe with Boon of the Earth
2. Mine lots of stone

### Expected behavior
Boon of the Earth only drops usable, naturally generating ores.

### Affected Version
- Pack Version: 2.1.0
- On a server?: Tested on official server

**Comment by Gbergz** [comment]
Will go ahead and fix this for a future update, thanks for the report!

**Comment by Gbergz** [comment]
Fixed in 2.2.0
