### ISSUE TITLE
FTB Chunk Loading and Create

### ISSUE THREAD

**Issue by Ayeitzralph** [The-Nexus-Project/Limitless-5#48]
I have a create hose pully pumping infinite lava in the nether and I have the area chunk loaded. Every time I return back to my base it unloads the machine or the chunk or something. When I go back the hose pully isnt fully down anymore and nothing is being pumped.

**Comment by Gbergz** [comment]
FTB Chunk loading isn't working correctly, and hans't been for quite long while now. This is known.
