### ISSUE TITLE
Loot Bags

### ISSUE THREAD

**Issue by Ayeitzralph** [The-Nexus-Project/Limitless-5#49]
Sometimes when I open lootbags my screen freezes for a second and I get nothing out of them

**Comment by Gbergz** [comment]
Which version of the pack are you on? Because you literally removed the issue layout.

**Comment by Ayeitzralph** [comment]
The most recent version 1.4.0

**Comment by newtrogicNexus** [comment]
2.1 is the most recent version.

**Comment by Ayeitzralph** [comment]
on curseforge it says im on the most modern version?

**Comment by Ayeitzralph** [comment]
oh it changed to 1.18.2
