### ISSUE TITLE
Create iron sheet can't be used in place of iron plates

### ISSUE THREAD

**Issue by hvdklauw** [The-Nexus-Project/Limitless-5#5]
1. make iron sheets with the create mechanical press
2. Try to make a propellor from create using those sheets
3. ...
4. Go into cheat mode to exchange your iron sheets for iron plates so you can make the propellor and thus continue with create.

Maybe tags (forge:plates/iron) should be for recipes instead of hard item ids, because the same goes for other plates/sheets!

**Comment by Gbergz** [comment]
fixed in v0.10.0
