### ISSUE TITLE
Index out of bounds exception

### ISSUE THREAD

**Issue by jeromecoder** [The-Nexus-Project/Limitless-5#50]
Hello,
everytime I want to connect to my server (self hosted) i get this error :
![image](https://user-images.githubusercontent.com/9369532/163857257-7b3acd2e-2ade-442d-9581-a5780ecff986.png)

No error in the log. Only these two lines 
![image](https://user-images.githubusercontent.com/9369532/163857506-1253aaa5-faf2-4994-aa75-52756a187ffb.png)

Can you help me ?

**Comment by Gbergz** [comment]
Yes if you didn't ignore the issue template that is used so I can know what version etc etc.

**Comment by Gbergz** [comment]
Closing since you're in discord aswell.

**Comment by Sonic1305** [comment]
Any info what the solution was?

**Comment by SikiciBebek** [comment]
Whats the solution? :c

**Comment by Gbergz** [comment]
Restarting client & server solves this.

**Comment by SikiciBebek** [comment]
It worked
Ty Sir! <3
