### ISSUE TITLE
[Issue] Wooden Cabinets

### ISSUE THREAD

**Issue by Hodgy2448** [The-Nexus-Project/Limitless-5#52]
### Describe your issue, what happened?
Placed a wooden cabinet and the world crashed and won't load back up

### To Reproduce

Placed a wooden cabinet
Error:
https://bytebin.lucko.me/goSxujVvVY

### Expected behavior
Freeze
Crash

### Crash Reports & Logs (Don't paste entire crash reports here.)
https://bytebin.lucko.me/goSxujVvVY

### Affected Version

- Pack Version: 2.1.0
- On a server?: Local-Host Open to LAN

**Comment by Gbergz** [comment]
Storage Cabinets are removed in 2.2.0, since it caused crashes.
Update modpack.

**Comment by Hodgy2448** [comment]
Perfect, its working thank you. Great pack

**Comment by Gbergz** [comment]
Great! :)
