### ISSUE TITLE
Blocks randomly disappear and gamerule settings reset on server restart

### ISSUE THREAD

**Issue by daemos898** [The-Nexus-Project/Limitless-5#53]
So when the server gets reset sometimes blocks in the world disappear, specifically around where players have built and gamerule settings reset, the gamerule changes are mob griefing and keep inventory, we have to change the settings every time the server is brought back up

**Comment by Gbergz** [comment]
This might be caused by the FTB Chunks forceload (chunkload) option. I would recommend not using it as it doesn't even work anyways.
