### ISSUE TITLE
Coke Oven and Blast Furnace Missing Recipes [Issue] 

### ISSUE THREAD

**Issue by mathfreak2** [The-Nexus-Project/Limitless-5#54]
### Describe your issue, what happened?

The recipes for both the coal coke block and the coal coke item are missing. I cannot insert items into the coke oven, and clicking "Show Recipes" in the GUI for it does not do anything. This is a major bug, as it seems that this is the only way to make steel, effectively making it impossible to progress to large sections of the modpack (with the possible exception of finding it in random loot and loot bags?)

Edit 1: I've also discovered that the blast furnace recipes are missing, too, as I tried to put iron and charcoal in the blast furnace, and neither worked.

### To Reproduce

1. Build Coke Oven
2. Try to make coal coke by inserting a coal block or item
3. Fail, because the recipe is missing

### Expected behavior

The ability to make coal coke by inserting coal into the coke oven

### Screenshots

![image](https://user-images.githubusercontent.com/8137398/164512315-c9a19f52-7dc7-45c0-9bdd-ef0ce420d05a.png)
![image](https://user-images.githubusercontent.com/8137398/164513412-03c354f2-391c-428f-be23-3e27f1d2f599.png)
![image](https://user-images.githubusercontent.com/8137398/164513582-3797612d-d3f8-4951-a7e8-a394ba34ef66.png)

### Affected Version

- Pack Version: v2.2.0
- On a server?: No

**Comment by Gbergz** [comment]
Hey, I can't seem to reproduce this. All of this above works as normal.

**Comment by mathfreak2** [comment]
Hmm. That's interesting, because I also tried closing and rebooting the pack, and I still had the same issue. Additionally, I haven't edited any config files for the modpack. So, I'm not sure what could be going on that's different for you.

**Comment by Gbergz** [comment]
This specific issue you're having was fixed in the 2.2.0 update actually. 
So I would try re-installing everything from scratch.

**Comment by mathfreak2** [comment]
Thanks. I'll try that.

**Comment by mathfreak2** [comment]
Oops. Yeah, looks like I was still on v2.1.0. Thanks for catching that; I will close the issue now.
