### ISSUE TITLE
[Issue] FTB utillites chunk loading not working

### ISSUE THREAD

**Issue by Hodgy2448** [The-Nexus-Project/Limitless-5#55]
### Describe your issue, what happened?

I have lava pumps set up in the nether and only work when a player is there. I have have chunks claimed and force loaded but doesn't work.

### Affected Version

- Pack Version: 2.2.0
- On a server?: Both

**Comment by Gbergz** [comment]
Known, it's being disabled next update as it's causing more issues than good right now.

**Comment by Hodgy2448** [comment]
Are there any work arounds? Thanks

Sent from my iPhone

On 22 Apr 2022, at 16:06, Gbergz ***@***.***> wrote:

﻿

Known, it's being disabled next update as it's causing more issues than good right now.

**Comment by Gbergz** [comment]
Nope, not right now.

**Comment by void513** [comment]
alternative if  you are using a Quantum Entangloporter to transport  lava to your base you use a anchor upgrade  on it to keep the  chunk loaded. or place a teleporter down close to pumps and use anchor upgade on it to keep chunk loaded loaded.

**Comment by Gbergz** [comment]
Latest update added the mod [Chunk Loaders](https://www.curseforge.com/minecraft/mc-mods/chunk-loaders). Use that mod.

**Comment by blacksythe** [comment]
Confirmed fixed in latest version of ftbchunks tested on my players and you need to remove chunk load then load it again
