### ISSUE TITLE
[Issue] Mekanism Universal Cable

### ISSUE THREAD

**Issue by TwistedChimp** [The-Nexus-Project/Limitless-5#56]
### Describe your issue, what happened?

Twice now, my Mekanism Ultimate Universal Cable has bugged.  Where the power being fed into it seems to just disappear - and drains batteries super fast.  This happened once coming back from a restart, and a second time using the /home command.  If I break all the cable and relay it, it's fine.  Until next time?

Even the light that shows the cable is powered disappears when this happens.

### Affected Version
  2.2.0 (I'm guessing also in 2.3.0)
- Pack Version: 
- On a server?:

**Comment by newtrogicNexus** [comment]
Wouldn't it make more sense to report this issue to the mekanism devs?

**Comment by TwistedChimp** [comment]
I could, I was guessing it may be a conflict with another mod possibly?   I'll report it to Mekanism then, sorry for the mis-post.
