### ISSUE TITLE
Can't spawn wither boss

### ISSUE THREAD

**Issue by TheLeftSeat** [The-Nexus-Project/Limitless-5#57]
### Are you using OptiFine?
No

### Describe your issue, what happened?
Tried to spawn wither boss in overworld and it won't spawn - just remains 4 soul sand and 3 wither skeleton heads.
Also tried to spawn it in the nether and the same thing happened.

### To Reproduce

1. Place soul sand in traditional "T" configuration (1 block, then 3 horiz blocks centered on1st block)
2. Place 2 wither skeleton heads on two of the horiz soul sand blocks
3. Have a shot of Vodka
4. Place 3rd wither skeleton head on last horiz soul sand block
5. Wither boss doesn't spawn. No visible change whatsoever.

Has space all around it, and is built on a bed of Mob Grinding Utils tinted glass, which is wither boss explosion proof.

difficulty=hard in server.properties.

This has worked in all other modpacks. 

### Expected behavior
Wither boss should spawn when last wither skeleton head is placed on soul sand arm.

### Screenshots
(none)

### Crash Reports & Logs (Don't paste entire crash reports here.)
(none)

### Affected Version

v2.1.0 server on Linux
v2.1.0 client on Windows 10
Yes, I know current version is 2.1.3 but I've got folks playing this who would love a fix if you've run into it and have an idea of what I need to fix.

**Comment by pooniomoment** [comment]
use soulstone from the mod bygone nether instead of soul sand
most commonly found in soul sand valleys

**Comment by Gbergz** [comment]
Not a bug. Soul Stone from Bygone Nether is used instead.

Soul Sand can be used again in the upcoming update. (V2.4.0).
