### ISSUE TITLE
[Issue] all mobs are invisible

### ISSUE THREAD

**Issue by lewisnova** [The-Nexus-Project/Limitless-5#58]
### Are you using OptiFine?
No additional mods
### Describe your issue, what happened?
Started a new single player world spawned in on the map and was getting attacked by mobs that were coming from a structure nearby, along with a seagul who nicked some food, the mobs killed me and i couldnt see them

### To Reproduce

1. Create new world
2. find where mobs would be
3. get killed cause you cant see them

### Expected behavior
to be able to see mobs 

### Screenshots
![2021-10-03](https://user-images.githubusercontent.com/9366581/165417488-b5028211-114d-4f69-8bf4-4f13d89a010e.png)
you can tell by the subtitles in the bottom right that there are mobs around me but both the mini map and on screen show no mobs

### Affected Version

- Pack Version: 2.3.0
- On a server?: N

**Comment by northreisende** [comment]
yes not only are mobs invisible, both hostile and passive. but other entities are also invisible, such as broken blocks and beds.  this is also on single player

**Comment by Gbergz** [comment]
restart clients if it happens.
