### ISSUE TITLE
[Issue] RFTools spawner, level 100 slime crashing game.

### ISSUE THREAD

**Issue by Hodgy2448** [The-Nexus-Project/Limitless-5#60]
### Describe your issue, what happened?

Using RFTools spawner, inserting level 100 slime crashing game

### To Reproduce

have a powered spawner, and matter beamer with level on (not sure if I needed a level but it was there and on)
insert syringe (mine was slime ,full)

### Expected behavior

exit to menu, with crash error

### Crash Reports & Logs (Don't paste entire crash reports here.)
 

https://bytebin.lucko.me/gGRgcHm7Zm

### Affected Version

- Pack Version: 1.3
- On a server?: no

**Comment by Hodgy2448** [comment]
Alongside of this, everything is invisible; mobs, hands

**Comment by Hodgy2448** [comment]
screenshots: https://imgur.com/a/YmmukU7

**Comment by Gbergz** [comment]
Restart client for the second issue.

**Comment by MoeHunt3r** [comment]
> Report the rftools issue to rftools.

https://github.com/McJtyMods/RFToolsUtility/issues/139
