### ISSUE TITLE
[Issue] Limestone Seeds from Mystical Agriculture can't be grown in the Garden Cloche 

### ISSUE THREAD

**Issue by IllegalCharacter** [The-Nexus-Project/Limitless-5#61]
### Describe your issue, what happened?

Limestone Seeds from Mystical Agriculture can't be grown in the Garden Cloche like the rest of the MA seeds can.

### To Reproduce

1. Put seeds in cloche with power/water/prudentium farmland
2. Nothing Happens

### Expected behavior
They should grow.

### Screenshots

Limestone:
![javaw_HYJx32vAvO](https://user-images.githubusercontent.com/7243508/165892503-c932a8f1-0b2c-4e22-a824-f5d238922d33.png)

Other seeds:
![javaw_MNWo3v4jU7](https://user-images.githubusercontent.com/7243508/165892524-670bb349-640e-41df-a044-8a809330f1f8.png)

Side note on MA, I think seeds should be able to use farmland of the same or a higher tier, instead of only the matching tier. That's more typical of MA in packs in my experience.

### Affected Version
- Pack Version: 2.2.0
- On a server?: Yes

**Comment by Gbergz** [comment]
I'll add support for this and any other new seed. Thanks for the report.
