### ISSUE TITLE
[Issue] 

### ISSUE THREAD

**Issue by Sapphire-Star22** [The-Nexus-Project/Limitless-5#62]
### Describe your issue, what happened?

The game took a while to start after clicking play, which is to be expected, but it never loaded, and the loading screen didn't ever pop up. It just gave me an unusual error code, Exit code-1073741819 (no further info, not even a crash report) which I've seen when i end Minecraft in general with task manager, or i end the process when a game freezes. but never when unsuccessfully opening the game. Sorry if that didn't make sense, I'm pretty stupid.
### To Reproduce

1. Click play
2. See error

### Expected behavior

the game was meant to start.
### Affected Version

- Pack Version: v2.3.0
- On a server?: no

**Comment by Gbergz** [comment]
Logs would help

**Comment by Sapphire-Star22** [comment]
no idea what happened, but restarting my computer fixed it. i forgot the first thing you should try before asking for help. sorry for wasting your time.
