### ISSUE TITLE
Crash with Botania Floating Pure Daisy

### ISSUE THREAD

**Issue by jjjworley** [The-Nexus-Project/Limitless-5#63]
Well, the game was extremely fun before this happened.

I pickaxed a dirt block out of the ground and put a bucket of water in the hole. Then I attempted to put a floating pure daisy in the water and the game crashed. Now the game crashes every time I try to start it. Is there any way to load the game a minute before the crash?

My memory is foggy, but a few years ago there was a program where you could load minecraft and move around in the game without the game actually running, so you could undo things that went wrong. Do you know what program that was?

**Comment by Gbergz** [comment]
This is known, any placed floating flower will crash you.
Recipes for them removed in 2.4.0.

**Comment by jjjworley** [comment]
I keep trying to update to 2.4.0, but I keep getting this message:

ModpackInstallTask - Unable to get file: AddonID: 548084, FileID: 3776146

So 2.4.0 won't install

**Comment by newtrogicNexus** [comment]
Curseforge API is down right now, but you can bypass it by downloading the pack files from the website and importing it into multimc/polymc.

**Comment by jjjworley** [comment]
Thanks! :)

**Comment by jjjworley** [comment]
I loaded a backup and was able to get back into my game. Thank you for all of your help, and thank you for all of your hard work making this awesome pack. I am having the time of my life with it!! :)
