### ISSUE TITLE
Pack not starting, only whitescreen

### ISSUE THREAD

**Issue by materschief** [The-Nexus-Project/Limitless-5#65]
### Are you using OptiFine?
Not using optifine.

### Describe your issue, what happened?
I started the pack with MultiMC and it just shows an whitescreen.

### To Reproduce

1. Start Multimc
2. Start Modpack
3. Whitescreen of Death

### Expected behavior
I expected to see the Loading screen of the pack and eventually play the pack.

### Screenshots
![NVIDIA_Share_2022-05-03_14-22-26](https://user-images.githubusercontent.com/848971/166452002-8a15694c-ccfc-4d6c-bc24-48dea30243c1.png)

### Crash Reports & Logs (Don't paste entire crash reports here.)
https://pastebin.com/fALTvDaq

### Hardware used 
CPU: Intel i9 9900k
GPU: Nvidia RTX 2080ti
RAM: 32GB
Drive: Sata SSD´s

### Affected Version

- Pack Version: 2.4.0
- On a server?: No
- Java version: 17.0.3.1
- 32 or 64 bit: 64 Bit
- MultiMC: 5 Version 0.6.16-develop-3282

**Comment by Gbergz** [comment]
Go into the config folder -> Open the file "fml.toml" change maxThreads from -1 to 3

**Comment by materschief** [comment]
Thanks for the fast reply. That worked.

**Comment by Gbergz** [comment]
This should be fixed without editing any configs in v2.5.0 and above.
