### ISSUE TITLE
[Issue] Chunk loaders

### ISSUE THREAD

**Issue by Hodgy2448** [The-Nexus-Project/Limitless-5#66]
### Describe your issue, what happened?

Chunk loaders - chunk loaders not chunk loading

### To Reproduce

Place chunk loader
Go another dimension
place chunk loader

### Expected behavior

No power recieved from tesseracts (showing signs of chunks not loading because tesseracts work in same chunk)

### Affected Version

- Pack Version:  2.4.0
- On a server?: No

**Comment by Gbergz** [comment]
Hey, just tried this. Works fine for me using a Single Chunkloader. 🤔

**Comment by Hodgy2448** [comment]
I'm unsure about this, I will test again tomorrow

**Comment by blacksythe** [comment]
ftbchunks working with latest version on curseforge confirmed by several of our players by unloading the chunk on the ftbchunks map then re loading it.
