### ISSUE TITLE
Copper Anvil Dupe Glitch

### ISSUE THREAD

**Issue by Umber0010** [The-Nexus-Project/Limitless-5#67]
The Copper Anvil from the mod "Everything is Copper" does not properly consume items. Attempting to repair an item using it will give you the repaired item, along with a copy of the unrepaired item and whatever materials should have been consumed.

Steps to reproduce: 

1. Obtain a copper Anvil
2. Obtain Damaged equipment and the material needed to repair it
3. Attempt to repair equipment
4. Obtain more items than you put into the anvil.

Unknown if this applies to combining/enchanting items. However, it does seem likely.

**Comment by Gbergz** [comment]
https://github.com/JDKDigital/everythingcopper/issues/1
