### ISSUE TITLE
Cannot see attributes for Liquid Crystal in Deep Resonance

### ISSUE THREAD

**Issue by jjjworley** [The-Nexus-Project/Limitless-5#68]
Cannot see attributes for strength, purity and efficiency when looking at tank containing liquid crystal, so cannot refine to proper levels.

Also, laser lens uncraftable.

**Comment by Gbergz** [comment]
Better to report to the Rftools dev themselves I think.

**Comment by jjjworley** [comment]
I opened an issue on Deep Resonance. Thanks

**Comment by jjjworley** [comment]
McJty said The One Probe mod by him is necessary to view the attributes. Would it be possible to incorporate this mod?

**Comment by Gbergz** [comment]
Probably not, using Jade and won't swap.
Sorry for late reply.
Ask Jade dev if this could be implemented!
