### ISSUE TITLE
[Issue] dripstone not generate lava in cauldron

### ISSUE THREAD

**Issue by juanretamales** [The-Nexus-Project/Limitless-5#69]
### Are you using OptiFine?
No, is pure instance

### Describe your issue, what happened?
the lava farm doesn't work since the last update, I don't know if it's because of some mod or it's really a bug

### To Reproduce
1. set a simple lava farm with a cauldron
2. wait
3. not apear lava (in of game hours)

### Expected behavior
-

### Screenshots
![2022-05-05_19 24 15](https://user-images.githubusercontent.com/8421263/167042888-379853ab-b37c-4bdc-b569-bafe20d5d78a.png)

### Crash Reports & Logs (Don't paste entire crash reports here.)
-

### Affected Version
- Pack Version:  2.4.0
- On a server?: No

**Comment by Gbergz** [comment]
This would be kinda hard to debug and find out what mod causes this. Hm..

**Comment by juanretamales** [comment]
I really only reported it so that they take it into account, if it is due to some mod, when they are testing an update it could be solved.

**Comment by Gbergz** [comment]
Yes, I will test indev to see if it's solved, will update this issue if it is some day. :)

**Comment by VladimirMangos** [comment]
https://github.com/AOCAWOL/BYG/issues/746

**Comment by Gbergz** [comment]
@juanretamales well there you go. :) Will be fixed in the next byg update.

**Comment by VladimirMangos** [comment]
Oh_The_Biomes_You'll_Go-forge-1.18.2-1.4-all-RC-12 released
