### ISSUE TITLE
Lootbags only seem to contain lag

### ISSUE THREAD

**Issue by SekhetBR** [The-Nexus-Project/Limitless-5#7]
They just lag the game for a few seconds when opened. No items or whatnot.

**Comment by Gbergz** [comment]
Hey,
Can't reproduce this.

**Comment by SekhetBR** [comment]
No, I just opened them after getting them as quest rewards in the new update. No edits, mod additions, subtractions, config changes, so on - playing the pack As Is. Two bags total, both of them showed this behavior. 

I assume I'll get some more lootbags as I progress, so I'll post what happens with them.

**Comment by Gbergz** [comment]
If that doesn't work can you try updating the mod? It recently got an update. See if that makes a difference.

**Comment by Gbergz** [comment]
Usually when you get no items the config didn't get read properly, try going into the world then serverconfig. Leave / stop server.
Then remove the file "lootbagmod-server.toml" and rejoin server/world.

**Comment by SekhetBR** [comment]
I'll back up the world and give all of that a try if it happens again

**Comment by Maltmannn** [comment]
I came to report this bug as well, did updating the mod work?

**Comment by Gbergz** [comment]
try regenerating the lootbag config in your world folder (under serverconfig). quit world first then restart.

**Comment by Maltmannn** [comment]
That worked thanks.

**Comment by Maltmannn** [comment]
It seems that it happened again after a while, but whenever I restart the game its back to normal. Didn't have to reset the config just had to restart the game.

**Comment by Gbergz** [comment]
Yeah a weird issue, never had it myself like ever (yet).

**Comment by Maltmannn** [comment]
Any plans to expand quests for Create and other mods?

**Comment by Gbergz** [comment]
> Any plans to expand quests for Create and other mods?  
Yes. Some comes next update. Create I don't know that well so I can't create a chapter for it.

Join the discord and check upcoming update. https://discord.gg/gwzpyQb
