### ISSUE TITLE
When I shut my server down and login the next day all players reset 

### ISSUE THREAD

**Issue by randybeck** [The-Nexus-Project/Limitless-5#70]
The only things retained are whatever was in the main inventory. I lose everything in the backpack, waystones reset, map resets, and achievements all show as being completed upon login. Any fix for this?

**Comment by Gbergz** [comment]
Absolutely weird and annoying, though this I can't reproduce..

Hmm..

**Comment by randybeck** [comment]
I tried many things. I re downloaded the the server, tried old world backups, tried and entirely new world, tried to locate specific mods that caused this or similar issue with other people (essentials), looked through game files to see what else could be it. Only thing I saw was in the user cache it says each user expires same day so that could be it? Also saw where some people saw a similar issue like this when the server doesn’t recognize uuid but I’m not sure how to fix that. It also doesn’t explain how we still have our inventory
