### ISSUE TITLE
Charm Belt has broken GUI

### ISSUE THREAD

**Issue by ShawnKilbride** [The-Nexus-Project/Limitless-5#72]
The charm belt's GUI is broken.
![image](https://user-images.githubusercontent.com/56053226/167262068-99670ee7-0e4d-465e-9db4-346faafc0bd1.png)

**Comment by Gbergz** [comment]
Are you sure? I've tried just now and it isn't broken.
Have you added any extra mods? And why is the issue template gone? I need mostly all that info.. :s

**Comment by ShawnKilbride** [comment]
I have not added any extra mods. I'm using v2.4.0 of the pack.

**Comment by Gbergz** [comment]
Hm, alright. 
Tried restarting the game?
I've tried to reproduce the issue though I am unable to..
