### ISSUE TITLE
Storage disks disappearing

### ISSUE THREAD

**Issue by MoistPork** [The-Nexus-Project/Limitless-5#74]
While playing on a private server the storage disks disappear every other time the server goes down, my friend who runs the server try's to fix things to the best of his ability but we're unable to figure out why it's just the storage disks that disappear. If someone can help figure this out it would be much appreciated.

**Comment by Gbergz** [comment]
This is known, and is probably a bug in Refined Storage. Looking at their issue tracker it has been reported for 1.16 and 1.18.
