### ISSUE TITLE
The "Move All Matching Items" arrow and the Mining Gadget filter menu 

### ISSUE THREAD

**Issue by Oreo735** [The-Nexus-Project/Limitless-5#75]
I'm not sure what mod it it, it's the one that adds Inventory buttons like sort by columns and move all matching items.
### Are you using OptiFine?
No

### Describe your issue, what happened?

Using a Mining Gadget MK3 with filter upgrade, opening the filter menu and pressing Shift + Move All Matching Items arrow moves items from player inventory to the mining gadget filter menu, once the items are in the filter menu they are non retrievable.  
### To Reproduce

1. Go to 'Mining Gadget MK3 Filter Menu'
2. Click on 'Shift + Move All Matching Items'
3. Your Inventory is gone

### Screenshots

![Screenshot (1)](https://user-images.githubusercontent.com/65066753/168441052-cdb958d4-8ad5-4f52-9533-83a52dde8138.png)

### Affected Version

- Pack Version: 2.5.2
- On a server?: https://feedthecraft.com/

**Comment by Gbergz** [comment]
I'll blacklist this GUI next update to prevent it from happening again.

**Comment by Gbergz** [comment]
Blacklisted in 2.6.0
