### ISSUE TITLE
Tinker's Construct Smeltery Controller

### ISSUE THREAD

**Issue by KamieChimera** [The-Nexus-Project/Limitless-5#76]
### Describe your issue, what happened?

Using Tinker's Construct works in Vanilla Minecraft biomes, however when a smeltery is placed and set up in non-vanilla biomes, such as BYG (Biomes You'll Go) or Biomes OP. it fails to properly work, and will consume fuel at an abnormal rate, regardless of size.
When using the smeltery, the GUI lists 0 fuel, and likewise, no temperature. As a result, it has incorrect tick times for each lava bucket, consuming half a seared fuel tank with 3 ores smelted.

### To Reproduce

1. Go to a Vanilla biome, Set up a smeltery and right click the smeltery controller.
2. Once checked that it's working, head to a non-vanilla biome. A possible list is below --
     **- Allium Fields** 
     (https://oh-the-biomes-youll-go.fandom.com/wiki/Allium_Fields)
     **- Cherry Blossom Forest** 
     (https://oh-the-biomes-youll-go.fandom.com/wiki/Cherry_Blossom_Forest)
     **- Mangrove Marshes**
     (https://oh-the-biomes-youll-go.fandom.com/wiki/Mangrove_Marshes)
     **- Lavender Fields**
     (https://biomesoplenty.fandom.com/wiki/Lavender_Fields)
     **- Lush Savannah**
     (https://biomesoplenty.fandom.com/wiki/Lush_Savanna)
     **- Redwood Forest**
     (https://biomesoplenty.fandom.com/wiki/Redwood_Forest)
3. Right click the Smeltery Controller, and you should see 0 fuel being located inside the GUI. You should notice that the error is present if you see "No fuel" in the GUI 

### Expected behavior

See above. 
Expected behavior to be normal and properly consuming fuel.
### Screenshots

**Biomes You'll Go F3 (Lush Stacks)**
![byglushstacksf3](https://user-images.githubusercontent.com/105662428/168641356-e5614298-c7dd-439e-970e-57fa35d828a9.png)
**BYG Smeltery Controller**
![bygsmeltery](https://user-images.githubusercontent.com/105662428/168641457-28a1728f-c4dc-4ca3-b307-eeb1a5a65726.png)
**Vanilla F3 (Meadow)**
![unknown](https://user-images.githubusercontent.com/105662428/168642327-8b1458bb-1d49-4ea8-93c7-89b401677c94.png)
**Vanilla Smeltery Controller**
![unknown](https://user-images.githubusercontent.com/105662428/168642430-df06cc39-a8c9-4156-abb0-c19f33360bcb.png)
**Biomes OP F3 (Bayou)**
![unknown](https://user-images.githubusercontent.com/105662428/168642929-c9be5abe-75e1-4b47-95a4-f0b2a323aeb0.png)
**Biomes OP Smeltery Controller**
![unknown](https://user-images.githubusercontent.com/105662428/168643340-844e3322-d5e9-4937-9e5b-df7112a7f93f.png)

### Affected Version
- Pack Version: TNP Limitless 5 - 2.6.0
- On a server?: Yes. Privately run.

**Comment by Gbergz** [comment]
You should probably report this to Tinker's Construct.
Copy and paste it, not much I can do if its a mod problem.

**Comment by Gbergz** [comment]
Just tested this myself, and I can't reproduce the issue 🤔

**Comment by KamieChimera** [comment]
Well, got a response from them. Slimeknight was rather rude, and blamed optifine being mentioned rather than bothering to read my report. 

I even stated I tested without it too.

**Comment by KamieChimera** [comment]
Hm... Perhaps its a modpack issue. I had issues specifically in the biomes
I showed via screenshots. Did you try those? I noticed sometimes it
functions however sometimes it does not.

**Comment by Gbergz** [comment]
Don't think it's a modpack issue, I can't reproduce the issue you've reported at all actually.

**Comment by KamieChimera** [comment]
Which biome did you test?

**Comment by KamieChimera** [comment]
I can confirm restarting the server in a Lush Stacks biome through BYG does not function. I have also restarted the server twice, and rebuilt the smeltery in different sizes.

**Comment by Gbergz** [comment]
Tested in about 10 different byg and bop biomes, along with the magic forest biome mod.

**Comment by KamieChimera** [comment]
Hm... I am genuinely confused.

**Comment by KamieChimera** [comment]
Very strange. Let me try and restart the server and check if it functions
correctly after.

**Comment by KamieChimera** [comment]
I genuinely am unsure what started the issue. I will keep testing.
