### ISSUE TITLE
[Issue] All of the debug logs

### ISSUE THREAD

**Issue by blacksythe** [The-Nexus-Project/Limitless-5#77]
### Describe your issue, what happened?
Debug Folder Created over 100 gigabytes of debug logs

### To Reproduce

1. Host public Server
2. Have enough players online for a few weeks

### Expected behavior

Debugging is fine not cleaning up after itself is not

### Screenshots

![image](https://user-images.githubusercontent.com/11398873/168692870-69f7fb35-6429-4bcf-8b14-078e8a2f3d30.png)

### Affected Version

- Pack Version: 
- On a server?: TNP 5 Limitless 2.5.2

### Additional Mods that I we added to the pack

mc2discord-forge-1.18.x-3.2.5.jar
worldedit-mod-7.2.10.jar
Chunky-1.2.164.jar
architectury-4.4.59.jar
dynview-1.18.2-2.7.jar
EasierSleeping-1.18.2-2.1.0.jar
observable-2.2.3-forge.jar
radium-0.7.10.jar
adaptive_performance_tweaks_core_1.18.2-3.5.1.jar
adaptive_performance_tweaks_gamerules_1.18.2-3.5.1.jar

By the time you read this i will have checked each of the above to ensure they are not the culprit will post confirmation and close if they are.

Only possible culprit out of the above was adaptive performance tweaks. Idont think it was the cause though

**Comment by Gbergz** [comment]
I've had our public servers for Limitless 5 online for months, no logs ever get that big over time..

I would check with the extra mods you added on the server.
