### ISSUE TITLE
Server wont start up with default server files

### ISSUE THREAD

**Issue by tygramynta** [The-Nexus-Project/Limitless-5#8]
I download the latest server files and unzipped them. hit start server and it goes through its process and i type true for the EULA very shortly after it throws this error

Error: Could not find or load main class @libraries.net.minecraftforge.forge.1.18.1-39.0.14.win_args.txt

seems to be somethings related to the version of forge it comes with.

reisntalled the server files a couple times as well to no avail.

**Comment by Gbergz** [comment]
Is Java 17 your default Java version? This might happen if it's not.

**Comment by Gbergz** [comment]
Is Java 17 your default Java version? This might happen if it's not.

**Comment by Gbergz** [comment]
Looks like you solved this in the discord. Closing.
