### ISSUE TITLE
[Issue]  When applying a refined storage cable to a grid, game crashes, and reloads as corrupted chunks. Will post evidence later*

### ISSUE THREAD

**Issue by TommyGun1972** [The-Nexus-Project/Limitless-5#80]
### Are you using OptiFine?
No, i would assume built in because of the scoping in TNP 5.

### To Reproduce

1. Server with friends
2. apply refined storage cable
3. Uknown crash*
4. Reloading of corrupted chunks

### Expected behavior
Corrupted Chunks

### Affected Version

- Pack Version: 1.10.2
- On a server?: Yes

**Comment by Gbergz** [comment]
reopen if you have tha "evidence later".
