### ISSUE TITLE
[Issue] Using Fullscreen Mode in Pack Causes Moniter Issues

### ISSUE THREAD

**Issue by Bit-Flare** [The-Nexus-Project/Limitless-5#83]
### Describe your issue, what happened?
After updating to 2.7.0 when loading the pack in fullscreen mode and tabing out/using my other monitor, or switching to fullscreen mode when in the pack, severe visual distortions occur in the top 2/3rd of the screen. The distortions are most severe in the monitor's designed refresh rate of 75 hz. This occurs in the menu or in game, and both in single player and on a server. Returning to version 2.6.0 Fixes the issue. Repairing the pack does not resolve the issue

### To Reproduce

1. Load into pack in fullscreen mode
2. Tab out of pack
or
1. Switch into fullscreen mode while pack is open

### Expected behavior
No visual issues

### Video
https://photos.app.goo.gl/RQgjtHmH3Hb9UoT66

### Crash Reports & Logs (Don't paste entire crash reports here.)
[latest.log](https://github.com/The-Nexus-Project/Limitless-5/files/8773698/latest.log)

### Affected Version
- Pack Version: 2.70
- On a server?: N/A

**Comment by Gbergz** [comment]
Don't think this is a pack issue.
I can't reproduce this issue.
Currently playing myself and tested, nothing. Can't reproduce.
