### ISSUE TITLE
Missing recipes

### ISSUE THREAD

**Issue by MShrieken** [The-Nexus-Project/Limitless-5#85]
There seem to be a few ores that don't have processing recipes.

1. Dimension Shard Ore can't be ground down into anything. If you pick it up with silktouch it becomes basically useless unless you place it down and re-break it.
2. Deepslate Certus Quartz Ore does not share the same processing recipes as regular Certus Quartz ore.
3. Ruby ores can be made into dirty slurry, then into clean slurry, but we can't go anywhere after that.

Not missing, but it would be nice if Silent Gems ores could be enriched into two gems, similar to diamonds and emeralds, rather than smelting them into a single gem being the only processing method.

**Comment by Gbergz** [comment]
Most of these are mod issues rather than specific pack issues. I will look into these however.
