### ISSUE TITLE
Server Crashing[Issue] 

### ISSUE THREAD

**Issue by XJayWithOuttaX** [The-Nexus-Project/Limitless-5#86]
### Describe your issue, what happened?
the server is crashing i have no idea why.

### To Reproduce

joining the server

### Expected behavior
be able to play

### Affected Version

- Pack Version: TNP LimitLess 5 v2.7.1
- On a server?:yes

[crash-2022-05-25_11.44.19-fml.txt](https://github.com/The-Nexus-Project/Limitless-5/files/8792709/crash-2022-05-25_11.44.19-fml.txt)

**Comment by Gbergz** [comment]
Have you tried to restart it even once yet?

**Comment by XJayWithOuttaX** [comment]
yes, i did. the issue was mcaws lights

**Comment by Gbergz** [comment]
So, is it working now after that restart?
