### ISSUE TITLE
Right clicking mystical agriculture plant with item in hand causes seed to be dropped

### ISSUE THREAD

**Issue by molee446** [The-Nexus-Project/Limitless-5#9]

**Comment by Gbergz** [comment]
?

**Comment by molee446** [comment]
Usually when I right click to harvest one of the plants with no item in hand I don't get a seed but everytime when I right click harvest a plant with an item in hand I get a seed.

**Comment by Gbergz** [comment]
Hm, not sure this is a bug I can fix honestly.
Try reproducing it in an empty instance then report to Mystical Agriculture.

**Comment by molee446** [comment]
Makes sense thanks for your time. :)
