### ISSUE TITLE
Recipe Suggestions-Ore Berry Processing

### ISSUE THREAD

**Issue by Spontaneo** [The-Nexus-Project/Limitless-5#91]
So decided to make ore berries more viable by adding some automation options to processing the berries outside of smelting.   The crafting path is create:compacting to make the berry juice and then crossroads:centrifuge to process the juice.  The output values could be w/e but at least the option would be there.

[Compacting Recipes](https://github.com/Spontaneo/TNP5-scrap-board/tree/centrifuge)     
[Centrifuge Recipes](https://github.com/Spontaneo/TNP5-scrap-board/tree/compacting)

**Comment by Gbergz** [comment]
added in 2.9.0 :)
