### ISSUE TITLE
[Issue] 

### ISSUE THREAD

**Issue by Kirbmyster** [The-Nexus-Project/Limitless-5#94]
### Are you using OptiFine?

No
### Describe your issue, what happened?

Hero's medallion refuses to drain any levels can only return levels after update. glowing effect shows that the item is active in its current "drain" state, but has no action. 
### To Reproduce

Unsure. Mayhaps caused by update.
### Expected behavior

Item it meant to drain levels into displayed object to hold for later use.
### Screenshots

![2022-06-05_03 56 29](https://user-images.githubusercontent.com/106883934/172020061-8b1d8d86-7173-4067-9285-ac9ed8c7f70f.png)
![2022-06-05_03 56 39](https://user-images.githubusercontent.com/106883934/172020067-c19b69a6-c81e-443d-839d-d3b616ceb1db.png)

### Crash Reports & Logs (Don't paste entire crash reports here.)
 

N/a
### Affected Version

- Pack Version: 2.8.2
- On a server?: Yes

**Comment by Gbergz** [comment]
This isn't a case after this recent pack update, this has been an issue since I added the mod.
Probably just an issue within the mod itself because I've also experienced this behaviour.

**Comment by Gbergz** [comment]
https://github.com/P3pp3rF1y/Reliquary/issues

**Comment by Kirbmyster** [comment]
Shame that it's an issue, but oh well, thank you for the heads up and the quick reply. :)
