### ISSUE TITLE
No Paper Tools in Tinker's Construct?

### ISSUE THREAD

**Issue by RetroGuyGaming** [The-Nexus-Project/Limitless-5#97]
From what I can tell Tinker's is supposed to have paper tools still? Specifically the tool binding in my case. I have looked to see if maybe the creator of the modpack wanted to remove the paper tools but I didn't find any information or anyone else reporting this issue. I am currently using 2.6.0 but checked all future patch notes and didn't see that they added anything or did a bug fix for Tinker's. If it isn't supposed to be in the modpack that is fine I just didn't know if it was intended or if I was missing something. I looked for the paper stack used to make paper tools and it isn't there.

Thanks!

**Comment by Gbergz** [comment]
Paper parts, tools etc is not in the mod. Not on us.
