### ISSUE TITLE
Create tool box disconnect

### ISSUE THREAD

**Issue by timingplanet** [The-Nexus-Project/Limitless-5#98]
My friend when placing a white create tool box gets disconnected instantly video of it here https://youtu.be/DNuz6gT7ijE
We are on the latest version on as 7gb bisect server.
[latest (2).log](https://github.com/The-Nexus-Project/Limitless-5/files/8874054/latest.2.log)
[crashlog.txt](https://github.com/The-Nexus-Project/Limitless-5/files/8874064/crashlog.txt)

**Comment by Gbergz** [comment]
So, is this still happening on the latest pack update? If you're still playing.

**Comment by timingplanet** [comment]
Idk im not playing minecraft in general due to the whole bs moderation
system so no clue
